"use client";

import Link from "next/link";
import { useMemo, useState, useTransition, type ReactNode } from "react";
import { LegalRuleDialog } from "@/components/inference/legal-rule-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { AnalysisModuleDefinition } from "@/domain/analysis-modules";
import { obligationTypeLabels, obligationTypes, type ObligationType } from "@/domain/estate-settlement";
import { cn } from "@/lib/utils";
import type { ApiFact, InferenceRun } from "@/modules/contracts";

interface InitialCase { id: string; title: string; subject: string; facts: ApiFact[] }
interface Obligation { id: string; label: string; type?: ObligationType; amount?: number }
interface Beneficiary { id: string; name: string }
interface Distribution { id: string; label: string; beneficiaries: Beneficiary[]; complete?: boolean; sharesSpecified?: boolean; alternativeAgreement?: boolean }
type Mode = "payment" | "distribution";

const owned = new Set(["estate-obligation", "obligation-type", "obligation-label", "obligation-amount", "testamentary-distribution-group", "distribution-group-label", "distribution-beneficiary", "distribution-beneficiary-label", "distribution-beneficiary-set-complete", "testamentary-shares-specified", "alternative-share-agreement"]);

export function EstateSettlementWorkspace({ module, initialCase }: { module: AnalysisModuleDefinition; initialCase?: InitialCase }) {
  const restoredObligations = useMemo(() => restoreObligations(initialCase?.facts ?? []), [initialCase?.facts]);
  const restoredDistributions = useMemo(() => restoreDistributions(initialCase?.facts ?? []), [initialCase?.facts]);
  const [mode, setMode] = useState<Mode>(restoredDistributions.length && !restoredObligations.length ? "distribution" : "payment");
  const [obligations, setObligations] = useState(restoredObligations);
  const [distributions, setDistributions] = useState(restoredDistributions);
  const [obligationId, setObligationId] = useState(restoredObligations[0]?.id);
  const [distributionId, setDistributionId] = useState(restoredDistributions[0]?.id);
  const [run, setRun] = useState<InferenceRun>();
  const [error, setError] = useState<string>();
  const [ruleId, setRuleId] = useState<string>();
  const [pending, startTransition] = useTransition();
  const activeObligation = obligations.find((item) => item.id === obligationId);
  const activeDistribution = distributions.find((item) => item.id === distributionId);
  const facts = useMemo(() => [...obligationFacts(obligations), ...distributionFacts(distributions)], [obligations, distributions]);
  const results = useMemo(() => new Map(run?.results.map((item) => [`${item.predicate}:${item.subject}`, item]) ?? []), [run]);
  const ordered = useMemo(() => obligations.map((item, index) => ({ item, index, priority: priorityOf(results.get(`payment-priority:${item.id}`)?.value) })).sort((a, b) => (a.priority ?? 99) - (b.priority ?? 99) || a.index - b.index), [obligations, results]);

  function changed() { setRun(undefined); }
  function addObligation() { const id = uid("obligation"); setObligations((items) => [...items, { id, label: `Khoản ${items.length + 1}` }]); setObligationId(id); changed(); }
  function updateObligation(update: Partial<Obligation>) { if (!activeObligation) return; setObligations((items) => items.map((item) => item.id === activeObligation.id ? { ...item, ...update } : item)); changed(); }
  function removeObligation() { if (!activeObligation) return; const next = obligations.filter((item) => item.id !== activeObligation.id); setObligations(next); setObligationId(next[0]?.id); changed(); }
  function addDistribution() { const id = uid("distribution"); setDistributions((items) => [...items, { id, label: `Nhóm định đoạt ${items.length + 1}`, beneficiaries: [] }]); setDistributionId(id); changed(); }
  function updateDistribution(update: Partial<Distribution>) { if (!activeDistribution) return; setDistributions((items) => items.map((item) => item.id === activeDistribution.id ? { ...item, ...update } : item)); changed(); }
  function removeDistribution() { if (!activeDistribution) return; const next = distributions.filter((item) => item.id !== activeDistribution.id); setDistributions(next); setDistributionId(next[0]?.id); changed(); }
  function addBeneficiary() { if (!activeDistribution) return; updateDistribution({ beneficiaries: [...activeDistribution.beneficiaries, { id: uid("beneficiary"), name: `Người hưởng ${activeDistribution.beneficiaries.length + 1}` }], complete: undefined }); }
  function updateBeneficiary(id: string, name?: string) { if (!activeDistribution) return; updateDistribution({ beneficiaries: name === undefined ? activeDistribution.beneficiaries.filter((item) => item.id !== id) : activeDistribution.beneficiaries.map((item) => item.id === id ? { ...item, name } : item), complete: undefined }); }
  function infer() { if (!initialCase || facts.length === 0) return; startTransition(async () => { setError(undefined); try { const retained = initialCase.facts.filter((fact) => !owned.has(fact.predicate)); await json(`/api/cases/${initialCase.id}/facts`, { method: "PUT", body: JSON.stringify({ subject: initialCase.id, facts: [...retained, ...facts] }) }); setRun(await json<InferenceRun>(`/api/cases/${initialCase.id}/inference/estate-settlement`, { method: "POST", body: "{}" })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể chạy suy luận."); } }); }

  if (!initialCase) return null;
  return <div className="min-h-screen bg-background">
    <header className="border-b bg-card/80"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-3 px-4 py-3 sm:px-6"><div><p className="font-semibold">Inheritance Reasoner</p><p className="text-xs text-muted-foreground">{module.title} · R-I01/R-I02 · Điều 658–659</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant={mode === "payment" ? "default" : "outline"} onClick={() => setMode("payment")}>Thứ tự thanh toán</Button><Button size="sm" variant={mode === "distribution" ? "default" : "outline"} onClick={() => setMode("distribution")}>Chia đều theo di chúc</Button><Button asChild size="sm" variant="ghost"><Link href={`/cases/${initialCase.id}`}>Hồ sơ</Link></Button></div></div></header>

    {mode === "payment" ? <main className="mx-auto grid max-w-[1500px] gap-5 p-4 sm:p-6 xl:grid-cols-[300px_minmax(0,1fr)_420px]">
      <ListCard title="Các khoản cần trả" description="Loại khoản là input; mức ưu tiên là kết luận." action="Thêm khoản" empty={obligations.length === 0} onAdd={addObligation}>{obligations.map((item) => <Entity key={item.id} active={item.id === obligationId} title={item.label} detail={item.type ? obligationTypeLabels[item.type] : "Chưa phân loại"} onClick={() => setObligationId(item.id)} />)}</ListCard>
      <section>{activeObligation ? <Card><CardHeader><div className="flex justify-between"><Badge variant="outline">{activeObligation.id}</Badge><Button size="sm" variant="ghost" onClick={removeObligation}>Xóa</Button></div><CardTitle>Phân loại nghĩa vụ</CardTitle><CardDescription>R-I01 đối chiếu khoản này với bảng tri thức Điều 658.</CardDescription></CardHeader><CardContent className="space-y-5"><Field label="Tên gợi nhớ" value={activeObligation.label} onChange={(label) => updateObligation({ label })} /><label className="text-sm font-medium">Số tiền tham khảo<Input className="mt-2" type="number" min="0" value={activeObligation.amount ?? ""} onChange={(event) => updateObligation({ amount: event.target.value === "" ? undefined : Number(event.target.value) })} /></label><div className="flex justify-end"><Button size="sm" variant="ghost" onClick={() => setRuleId("R-I01")}>R-I01 · căn cứ</Button></div><div className="grid gap-2 sm:grid-cols-2">{obligationTypes.map((type, index) => <Choice key={type} selected={activeObligation.type === type} onClick={() => updateObligation({ type })}><span className="mr-2 inline-grid size-7 place-items-center rounded-full bg-muted font-mono text-xs">{index + 1}</span>{obligationTypeLabels[type]}</Choice>)}</div></CardContent></Card> : <Empty text="Thêm một khoản nghĩa vụ để bắt đầu." />}</section>
      <Result title={run ? `${ordered.length} khoản đã đối chiếu` : "Chưa chạy CLIPS"} error={error}>{run ? ordered.map(({ item, priority }) => <div key={item.id} className="flex gap-3 rounded-xl border p-3"><span className={cn("grid size-9 shrink-0 place-items-center rounded-full font-mono font-bold", priority ? "bg-primary text-primary-foreground" : "bg-amber-100")}>{priority ?? "?"}</span><div><p className="font-semibold">{item.label}</p><p className="text-xs text-muted-foreground">{item.type ? obligationTypeLabels[item.type] : "Thiếu loại nghĩa vụ"}</p>{priority ? <Button size="sm" variant="ghost" className="h-7 px-0 text-xs" onClick={() => setRuleId("R-I01")}>Điều 658</Button> : null}</div></div>) : <Placeholder>Thứ tự 1–10 sẽ xuất hiện sau suy luận.</Placeholder>}</Result>
    </main> : <main className="mx-auto grid max-w-[1500px] gap-5 p-4 sm:p-6 xl:grid-cols-[300px_minmax(0,1fr)_420px]">
      <ListCard title="Nhóm phân chia" description="Mỗi nhóm là một phần định đoạt theo di chúc." action="Thêm nhóm" empty={distributions.length === 0} onAdd={addDistribution}>{distributions.map((item) => <Entity key={item.id} active={item.id === distributionId} title={item.label} detail={`${item.beneficiaries.length} người được chỉ định`} onClick={() => setDistributionId(item.id)} />)}</ListCard>
      <section>{activeDistribution ? <Card><CardHeader><div className="flex justify-between"><Badge variant="outline">{activeDistribution.id}</Badge><Button size="sm" variant="ghost" onClick={removeDistribution}>Xóa</Button></div><CardTitle>Điều kiện chia đều theo di chúc</CardTitle><CardDescription>R-I02 chỉ nhận diện nguyên tắc, chưa tính phần của từng người.</CardDescription></CardHeader><CardContent className="space-y-6"><Field label="Tên nhóm" value={activeDistribution.label} onChange={(label) => updateDistribution({ label })} /><Question title="Di chúc đã xác định rõ phần của từng người?" onLaw={() => setRuleId("R-I02")}><BooleanChoice value={activeDistribution.sharesSpecified} onChange={(sharesSpecified) => updateDistribution({ sharesSpecified })} /></Question><Question title="Có thỏa thuận chia khác?" onLaw={() => setRuleId("R-I02")}><BooleanChoice value={activeDistribution.alternativeAgreement} onChange={(alternativeAgreement) => updateDistribution({ alternativeAgreement })} /></Question><div><div className="flex items-center justify-between gap-2"><p className="text-sm font-medium">Người được chỉ định</p><Button size="sm" variant="outline" onClick={addBeneficiary}>Thêm người</Button></div><div className="mt-2 space-y-2">{activeDistribution.beneficiaries.map((person) => <div key={person.id} className="flex gap-2"><Input value={person.name} aria-label={`Tên ${person.id}`} onChange={(event) => updateBeneficiary(person.id, event.target.value)} /><Button size="sm" variant="ghost" onClick={() => updateBeneficiary(person.id)}>Xóa</Button></div>)}{activeDistribution.beneficiaries.length === 0 ? <Placeholder>Chưa có người được chỉ định.</Placeholder> : null}</div></div><Question title="Danh sách người được chỉ định đã đầy đủ?" onLaw={() => setRuleId("R-I02")}><BooleanChoice value={activeDistribution.complete} onChange={(complete) => updateDistribution({ complete })} /></Question></CardContent></Card> : <Empty text="Thêm một nhóm định đoạt để bắt đầu." />}</section>
      <Result title={run ? `${distributions.length} nhóm đã đánh giá` : "Chưa chạy CLIPS"} error={error}>{run ? distributions.map((group) => { const result = results.get(`equal-testamentary-share-principle-applies:${group.id}`); const missing = run.missing.filter((item) => item.subject === group.id); return <div key={group.id} className="rounded-xl border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">{group.label}</p><ShareBadge value={result?.value} /></div><p className="mt-2 text-xs text-muted-foreground">{group.beneficiaries.map((item) => item.name).join(" · ") || "Chưa có người hưởng"}</p>{result?.value === "unknown" ? <p className="mt-2 text-xs text-amber-800">Thiếu: {missing.map((item) => missingLabel(item.predicate)).join("; ") || "dữ kiện chưa khớp"}</p> : null}{result?.derivations.includes("R-I02") ? <Button size="sm" variant="ghost" className="mt-2 h-7 px-0 text-xs" onClick={() => setRuleId("R-I02")}>R-I02 · Điều 659 khoản 1</Button> : null}</div>; }) : <Placeholder>CLIPS sẽ đánh giá riêng từng nhóm.</Placeholder>}</Result>
    </main>}

    <div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-3 px-4 pb-8 sm:px-6"><details><summary className="cursor-pointer text-xs font-medium text-muted-foreground">Xem {facts.length} facts Nhóm I</summary><div className="mt-3 max-h-52 overflow-auto rounded-lg bg-slate-950 p-3 text-[11px] text-slate-100">{facts.map((fact) => <code key={fact.id} className="block">{fact.predicate}({fact.subject}, {String(fact.value)})</code>)}</div></details><Button disabled={pending || facts.length === 0} onClick={infer}>{pending ? "CLIPS đang suy luận…" : "Lưu và chạy Nhóm I"}</Button></div>
    <footer className="px-6 pb-8 text-center text-xs text-muted-foreground">Prototype học tập · Không phải tư vấn pháp lý · Knowledge base chưa được phê duyệt chuyên môn</footer><LegalRuleDialog ruleId={ruleId} onOpenChange={(open) => { if (!open) setRuleId(undefined); }} />
  </div>;
}

function ListCard({ title, description, action, empty, onAdd, children }: { title: string; description: string; action: string; empty: boolean; onAdd: () => void; children: ReactNode }) { return <aside><Card><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle>{title}</CardTitle><Button size="sm" onClick={onAdd}>{action}</Button></div><CardDescription>{description}</CardDescription></CardHeader><CardContent className="space-y-2">{empty ? <button type="button" onClick={onAdd} className="grid min-h-28 w-full place-items-center rounded-xl border border-dashed text-sm text-muted-foreground">+ Tạo mục đầu tiên</button> : children}</CardContent></Card></aside>; }
function Entity({ active, title, detail, onClick }: { active: boolean; title: string; detail: string; onClick: () => void }) { return <button type="button" onClick={onClick} className={cn("w-full rounded-lg border p-3 text-left", active && "border-primary bg-primary/[0.05]")}><span className="block font-semibold">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{detail}</span></button>; }
function Result({ title, error, children }: { title: string; error?: string; children: ReactNode }) { return <aside><Card className="sticky top-4"><CardHeader><Badge variant="outline">Kết quả Nhóm I</Badge><CardTitle>{title}</CardTitle><CardDescription>Kết quả theo từng thực thể, chưa phân bổ tiền end-to-end.</CardDescription></CardHeader><CardContent className="space-y-3">{error ? <p className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}{children}</CardContent></Card></aside>; }
function Question({ title, onLaw, children }: { title: string; onLaw: () => void; children: ReactNode }) { return <div><div className="flex items-center justify-between gap-2"><p className="text-sm font-medium">{title}</p><Button size="sm" variant="ghost" onClick={onLaw}>R-I02 · căn cứ</Button></div><div className="mt-2">{children}</div></div>; }
function BooleanChoice({ value, onChange }: { value?: boolean; onChange: (value: boolean) => void }) { return <div className="grid gap-2 sm:grid-cols-2"><Choice selected={value === true} onClick={() => onChange(true)}>Có</Choice><Choice selected={value === false} onClick={() => onChange(false)}>Không</Choice></div>; }
function Choice({ selected, onClick, children }: { selected: boolean; onClick: () => void; children: ReactNode }) { return <button type="button" aria-pressed={selected} onClick={onClick} className={cn("rounded-lg border p-3 text-left text-sm font-medium", selected && "border-primary bg-primary/[0.06] ring-1 ring-primary")}>{children}</button>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-medium">{label}<Input className="mt-2" value={value} maxLength={200} onChange={(event) => onChange(event.target.value)} /></label>; }
function ShareBadge({ value }: { value?: string }) { return <Badge variant={value === "true" ? "success" : value === "false" ? "secondary" : "warning"}>{value === "true" ? "Áp dụng chia đều" : value === "false" ? "Không áp dụng mặc định" : "Chưa đủ dữ kiện"}</Badge>; }
function Placeholder({ children }: { children: ReactNode }) { return <div className="grid min-h-24 place-items-center rounded-xl border border-dashed px-4 text-center text-sm text-muted-foreground">{children}</div>; }
function Empty({ text }: { text: string }) { return <Card><CardHeader><CardTitle>Chưa có dữ liệu</CardTitle><CardDescription>{text}</CardDescription></CardHeader></Card>; }

function restoreObligations(facts: ApiFact[]): Obligation[] { return facts.flatMap((fact): Obligation[] => fact.predicate === "estate-obligation" && fact.value === true && fact.subject ? [{ id: fact.subject, label: String(find(facts, fact.subject, "obligation-label") ?? fact.subject), type: find(facts, fact.subject, "obligation-type") as ObligationType | undefined, amount: find(facts, fact.subject, "obligation-amount") as number | undefined }] : []); }
function restoreDistributions(facts: ApiFact[]): Distribution[] { return facts.flatMap((fact): Distribution[] => fact.predicate === "testamentary-distribution-group" && fact.value === true && fact.subject ? [{ id: fact.subject, label: String(find(facts, fact.subject, "distribution-group-label") ?? fact.subject), beneficiaries: facts.filter((item) => item.subject === fact.subject && item.predicate === "distribution-beneficiary").map((item) => ({ id: String(item.value), name: String(find(facts, String(item.value), "distribution-beneficiary-label") ?? item.value) })), complete: bool(find(facts, fact.subject, "distribution-beneficiary-set-complete")), sharesSpecified: bool(find(facts, fact.subject, "testamentary-shares-specified")), alternativeAgreement: bool(find(facts, fact.subject, "alternative-share-agreement")) }] : []); }
function obligationFacts(items: Obligation[]): ApiFact[] { return items.flatMap((item): ApiFact[] => { const facts: ApiFact[] = [{ id: `${item.id}-entity`, subject: item.id, predicate: "estate-obligation", value: true }, { id: `${item.id}-label`, subject: item.id, predicate: "obligation-label", value: item.label || item.id }]; if (item.type) facts.push({ id: `${item.id}-type`, subject: item.id, predicate: "obligation-type", value: item.type }); if (item.amount !== undefined) facts.push({ id: `${item.id}-amount`, subject: item.id, predicate: "obligation-amount", value: item.amount }); return facts; }); }
function distributionFacts(items: Distribution[]): ApiFact[] { return items.flatMap((group): ApiFact[] => { const facts: ApiFact[] = [{ id: `${group.id}-entity`, subject: group.id, predicate: "testamentary-distribution-group", value: true }, { id: `${group.id}-label`, subject: group.id, predicate: "distribution-group-label", value: group.label || group.id }]; group.beneficiaries.forEach((person, index) => facts.push({ id: `${group.id}-beneficiary-${index}`, subject: group.id, predicate: "distribution-beneficiary", value: person.id }, { id: `${person.id}-distribution-label`, subject: person.id, predicate: "distribution-beneficiary-label", value: person.name || person.id })); if (group.complete !== undefined) facts.push({ id: `${group.id}-complete`, subject: group.id, predicate: "distribution-beneficiary-set-complete", value: group.complete }); if (group.sharesSpecified !== undefined) facts.push({ id: `${group.id}-shares`, subject: group.id, predicate: "testamentary-shares-specified", value: group.sharesSpecified }); if (group.alternativeAgreement !== undefined) facts.push({ id: `${group.id}-agreement`, subject: group.id, predicate: "alternative-share-agreement", value: group.alternativeAgreement }); return facts; }); }
function find(facts: ApiFact[], subject: string, predicate: string) { return facts.find((fact) => fact.subject === subject && fact.predicate === predicate)?.value; }
function bool(value: ApiFact["value"] | undefined): boolean | undefined { return typeof value === "boolean" ? value : undefined; }
function priorityOf(value?: string): number | undefined { const number = Number(value); return Number.isInteger(number) && number >= 1 ? number : undefined; }
function uid(prefix: string) { return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`; }
function missingLabel(predicate: string) { return ({ "distribution-beneficiary-set-complete": "xác nhận danh sách đầy đủ", "distribution-beneficiary": "người được chỉ định", "testamentary-shares-specified": "di chúc có xác định phần", "alternative-share-agreement": "thỏa thuận chia khác" } as Record<string, string>)[predicate] ?? predicate; }
async function json<T = unknown>(url: string, init: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "content-type": "application/json", ...init.headers } }); const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error ?? `Request thất bại (${response.status}).`); return data; }
