"use client";

import Link from "next/link";
import { useMemo, useState, useTransition, type ReactNode } from "react";
import { LegalRuleDialog } from "@/components/inference/legal-rule-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { AnalysisModuleDefinition } from "@/domain/analysis-modules";
import { obligationTypeLabels, obligationTypes, type ObligationType } from "@/domain/estate-settlement";
import { cn } from "@/lib/utils";
import type { ApiFact, InferenceRun } from "@/modules/contracts";

interface InitialCase { id: string; title: string; subject: string; facts: ApiFact[] }
interface Obligation { id: string; label: string; type?: ObligationType; amount?: number }
interface Beneficiary { id: string; name: string }
interface Distribution { id: string; label: string; beneficiaries: Beneficiary[]; complete?: boolean; sharesSpecified?: boolean; alternativeAgreement?: boolean }
interface PrenatalAssessment { id: string; name: string; assessed: boolean; conceivedNotBorn: boolean; outcome?: "born-alive" | "died-before-birth" }
interface DivisionRestriction { id: string; basis?: "will-instruction" | "all-heirs-agreement"; allHeirsAgreed?: boolean; date?: string }
interface HardshipAssessment { id: string; name: string; assessed: boolean; divisionRequested?: boolean; seriousImpact?: boolean; priorExpired?: boolean; impactStillExists?: boolean }
type Mode = "payment" | "distribution" | "prenatal" | "restriction";

const owned = new Set(["estate-obligation", "obligation-type", "obligation-label", "obligation-amount", "testamentary-distribution-group", "distribution-group-label", "distribution-beneficiary", "distribution-beneficiary-label", "distribution-beneficiary-set-complete", "testamentary-shares-specified", "alternative-share-agreement", "prenatal-share-assessment-subject", "prenatal-status-at-distribution", "prenatal-birth-outcome", "division-restriction-assessment-subject", "division-restriction-basis", "all-heirs-agreed", "specified-division-date", "division-hardship-assessment-subject", "estate-division-requested", "serious-division-impact", "prior-court-deferral-expired", "serious-impact-still-exists"]);

export function EstateSettlementWorkspace({ module, initialCase }: { module: AnalysisModuleDefinition; initialCase?: InitialCase }) {
  const restoredObligations = useMemo(() => restoreObligations(initialCase?.facts ?? []), [initialCase?.facts]);
  const restoredDistributions = useMemo(() => restoreDistributions(initialCase?.facts ?? []), [initialCase?.facts]);
  const restoredPrenatal = useMemo(() => restorePrenatalAssessments(initialCase?.facts ?? []), [initialCase?.facts]);
  const restoredRestrictions = useMemo(() => restoreRestrictions(initialCase?.facts ?? []), [initialCase?.facts]);
  const restoredHardships = useMemo(() => restoreHardships(initialCase?.facts ?? []), [initialCase?.facts]);
  const [mode, setMode] = useState<Mode>(restoredPrenatal.some((item) => item.assessed) && !restoredDistributions.length && !restoredObligations.length ? "prenatal" : restoredDistributions.length && !restoredObligations.length ? "distribution" : "payment");
  const [obligations, setObligations] = useState(restoredObligations);
  const [distributions, setDistributions] = useState(restoredDistributions);
  const [prenatal, setPrenatal] = useState(restoredPrenatal);
  const [restrictions, setRestrictions] = useState(restoredRestrictions);
  const [hardships, setHardships] = useState(restoredHardships);
  const [obligationId, setObligationId] = useState(restoredObligations[0]?.id);
  const [distributionId, setDistributionId] = useState(restoredDistributions[0]?.id);
  const [prenatalId, setPrenatalId] = useState(restoredPrenatal[0]?.id);
  const [restrictionId, setRestrictionId] = useState(restoredRestrictions[0]?.id);
  const [hardshipId, setHardshipId] = useState(restoredHardships[0]?.id);
  const [run, setRun] = useState<InferenceRun>();
  const [error, setError] = useState<string>();
  const [ruleId, setRuleId] = useState<string>();
  const [pending, startTransition] = useTransition();
  const activeObligation = obligations.find((item) => item.id === obligationId);
  const activeDistribution = distributions.find((item) => item.id === distributionId);
  const activePrenatal = prenatal.find((item) => item.id === prenatalId);
  const activeRestriction = restrictions.find((item) => item.id === restrictionId);
  const activeHardship = hardships.find((item) => item.id === hardshipId);
  const facts = useMemo(() => [...obligationFacts(obligations), ...distributionFacts(distributions), ...prenatalFacts(prenatal), ...restrictionFacts(restrictions), ...hardshipFacts(hardships)], [obligations, distributions, prenatal, restrictions, hardships]);
  const results = useMemo(() => new Map(run?.results.map((item) => [`${item.predicate}:${item.subject}`, item]) ?? []), [run]);
  const ordered = useMemo(() => obligations.map((item, index) => ({ item, index, priority: priorityOf(results.get(`payment-priority:${item.id}`)?.value) })).sort((a, b) => (a.priority ?? 99) - (b.priority ?? 99) || a.index - b.index), [obligations, results]);

  function changed() { setRun(undefined); }
  function addObligation() { const id = uid("obligation"); setObligations((items) => [...items, { id, label: `Khoản ${items.length + 1}` }]); setObligationId(id); changed(); }
  function updateObligation(update: Partial<Obligation>) { if (!activeObligation) return; setObligations((items) => items.map((item) => item.id === activeObligation.id ? { ...item, ...update } : item)); changed(); }
  function removeObligation() { if (!activeObligation) return; const next = obligations.filter((item) => item.id !== activeObligation.id); setObligations(next); setObligationId(next[0]?.id); changed(); }
  function addDistribution() { const id = uid("distribution"); setDistributions((items) => [...items, { id, label: `Nhóm định đoạt ${items.length + 1}`, beneficiaries: [] }]); setDistributionId(id); changed(); }
  function updateDistribution(update: Partial<Distribution>) { if (!activeDistribution) return; setDistributions((items) => items.map((item) => item.id === activeDistribution.id ? { ...item, ...update } : item)); changed(); }
  function removeDistribution() { if (!activeDistribution) return; const next = distributions.filter((item) => item.id !== activeDistribution.id); setDistributions(next); setDistributionId(next[0]?.id); changed(); }
  function addBeneficiary() { if (!activeDistribution) return; updateDistribution({ beneficiaries: [...activeDistribution.beneficiaries, { id: uid("beneficiary"), name: `Người hưởng ${activeDistribution.beneficiaries.length + 1}` }], complete: undefined }); }
  function updateBeneficiary(id: string, name?: string) { if (!activeDistribution) return; updateDistribution({ beneficiaries: name === undefined ? activeDistribution.beneficiaries.filter((item) => item.id !== id) : activeDistribution.beneficiaries.map((item) => item.id === id ? { ...item, name } : item), complete: undefined }); }
  function updatePrenatal(update: Partial<PrenatalAssessment>) { if (!activePrenatal) return; setPrenatal((items) => items.map((item) => item.id === activePrenatal.id ? { ...item, ...update } : item)); changed(); }
  function addRestriction() { const id = uid("restriction"); setRestrictions((items) => [...items, { id }]); setRestrictionId(id); changed(); }
  function updateRestriction(update: Partial<DivisionRestriction>) { if (!activeRestriction) return; setRestrictions((items) => items.map((item) => item.id === activeRestriction.id ? { ...item, ...update } : item)); changed(); }
  function removeRestriction() { if (!activeRestriction) return; const next = restrictions.filter((item) => item.id !== activeRestriction.id); setRestrictions(next); setRestrictionId(next[0]?.id); changed(); }
  function updateHardship(update: Partial<HardshipAssessment>) { if (!activeHardship) return; setHardships((items) => items.map((item) => item.id === activeHardship.id ? { ...item, ...update } : item)); changed(); }
  function infer() { if (!initialCase || facts.length === 0) return; startTransition(async () => { setError(undefined); try { const retained = initialCase.facts.filter((fact) => !owned.has(fact.predicate)); await json(`/api/cases/${initialCase.id}/facts`, { method: "PUT", body: JSON.stringify({ subject: initialCase.id, facts: [...retained, ...facts] }) }); setRun(await json<InferenceRun>(`/api/cases/${initialCase.id}/inference/estate-settlement`, { method: "POST", body: "{}" })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể chạy suy luận."); } }); }

  if (!initialCase) return null;
  return <div className="min-h-screen bg-background">
    <header className="border-b bg-card/80"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-3 px-4 py-3 sm:px-6"><div><p className="font-semibold">Inheritance Reasoner</p><p className="text-xs text-muted-foreground">{module.title} · R-I01–R-I05 · Điều 658–661</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant={mode === "payment" ? "default" : "outline"} onClick={() => setMode("payment")}>Thanh toán</Button><Button size="sm" variant={mode === "distribution" ? "default" : "outline"} onClick={() => setMode("distribution")}>Chia theo di chúc</Button><Button size="sm" variant={mode === "prenatal" ? "default" : "outline"} onClick={() => setMode("prenatal")}>Người chưa sinh</Button><Button size="sm" variant={mode === "restriction" ? "default" : "outline"} onClick={() => setMode("restriction")}>Hạn chế chia</Button><Button asChild size="sm" variant="ghost"><Link href={`/cases/${initialCase.id}`}>Hồ sơ</Link></Button></div></div></header>

    {mode === "payment" ? <main className="mx-auto grid max-w-[1500px] gap-5 p-4 sm:p-6 xl:grid-cols-[300px_minmax(0,1fr)_420px]">
      <ListCard title="Các khoản cần trả" description="Loại khoản là input; mức ưu tiên là kết luận." action="Thêm khoản" empty={obligations.length === 0} onAdd={addObligation}>{obligations.map((item) => <Entity key={item.id} active={item.id === obligationId} title={item.label} detail={item.type ? obligationTypeLabels[item.type] : "Chưa phân loại"} onClick={() => setObligationId(item.id)} />)}</ListCard>
      <section>{activeObligation ? <Card><CardHeader><div className="flex justify-between"><Badge variant="outline">{activeObligation.id}</Badge><Button size="sm" variant="ghost" onClick={removeObligation}>Xóa</Button></div><CardTitle>Phân loại nghĩa vụ</CardTitle><CardDescription>R-I01 đối chiếu khoản này với bảng tri thức Điều 658.</CardDescription></CardHeader><CardContent className="space-y-5"><Field label="Tên gợi nhớ" value={activeObligation.label} onChange={(label) => updateObligation({ label })} /><label className="text-sm font-medium">Số tiền tham khảo<Input className="mt-2" type="number" min="0" value={activeObligation.amount ?? ""} onChange={(event) => updateObligation({ amount: event.target.value === "" ? undefined : Number(event.target.value) })} /></label><div className="flex justify-end"><Button size="sm" variant="ghost" onClick={() => setRuleId("R-I01")}>R-I01 · căn cứ</Button></div><div className="grid gap-2 sm:grid-cols-2">{obligationTypes.map((type, index) => <Choice key={type} selected={activeObligation.type === type} onClick={() => updateObligation({ type })}><span className="mr-2 inline-grid size-7 place-items-center rounded-full bg-muted font-mono text-xs">{index + 1}</span>{obligationTypeLabels[type]}</Choice>)}</div></CardContent></Card> : <Empty text="Thêm một khoản nghĩa vụ để bắt đầu." />}</section>
      <Result title={run ? `${ordered.length} khoản đã đối chiếu` : "Chưa chạy CLIPS"} error={error}>{run ? ordered.map(({ item, priority }) => <div key={item.id} className="flex gap-3 rounded-xl border p-3"><span className={cn("grid size-9 shrink-0 place-items-center rounded-full font-mono font-bold", priority ? "bg-primary text-primary-foreground" : "bg-amber-100")}>{priority ?? "?"}</span><div><p className="font-semibold">{item.label}</p><p className="text-xs text-muted-foreground">{item.type ? obligationTypeLabels[item.type] : "Thiếu loại nghĩa vụ"}</p>{priority ? <Button size="sm" variant="ghost" className="h-7 px-0 text-xs" onClick={() => setRuleId("R-I01")}>Điều 658</Button> : null}</div></div>) : <Placeholder>Thứ tự 1–10 sẽ xuất hiện sau suy luận.</Placeholder>}</Result>
    </main> : mode === "distribution" ? <main className="mx-auto grid max-w-[1500px] gap-5 p-4 sm:p-6 xl:grid-cols-[300px_minmax(0,1fr)_420px]">
      <ListCard title="Nhóm phân chia" description="Mỗi nhóm là một phần định đoạt theo di chúc." action="Thêm nhóm" empty={distributions.length === 0} onAdd={addDistribution}>{distributions.map((item) => <Entity key={item.id} active={item.id === distributionId} title={item.label} detail={`${item.beneficiaries.length} người được chỉ định`} onClick={() => setDistributionId(item.id)} />)}</ListCard>
      <section>{activeDistribution ? <Card><CardHeader><div className="flex justify-between"><Badge variant="outline">{activeDistribution.id}</Badge><Button size="sm" variant="ghost" onClick={removeDistribution}>Xóa</Button></div><CardTitle>Điều kiện chia đều theo di chúc</CardTitle><CardDescription>R-I02 chỉ nhận diện nguyên tắc, chưa tính phần của từng người.</CardDescription></CardHeader><CardContent className="space-y-6"><Field label="Tên nhóm" value={activeDistribution.label} onChange={(label) => updateDistribution({ label })} /><Question title="Di chúc đã xác định rõ phần của từng người?" onLaw={() => setRuleId("R-I02")}><BooleanChoice value={activeDistribution.sharesSpecified} onChange={(sharesSpecified) => updateDistribution({ sharesSpecified })} /></Question><Question title="Có thỏa thuận chia khác?" onLaw={() => setRuleId("R-I02")}><BooleanChoice value={activeDistribution.alternativeAgreement} onChange={(alternativeAgreement) => updateDistribution({ alternativeAgreement })} /></Question><div><div className="flex items-center justify-between gap-2"><p className="text-sm font-medium">Người được chỉ định</p><Button size="sm" variant="outline" onClick={addBeneficiary}>Thêm người</Button></div><div className="mt-2 space-y-2">{activeDistribution.beneficiaries.map((person) => <div key={person.id} className="flex gap-2"><Input value={person.name} aria-label={`Tên ${person.id}`} onChange={(event) => updateBeneficiary(person.id, event.target.value)} /><Button size="sm" variant="ghost" onClick={() => updateBeneficiary(person.id)}>Xóa</Button></div>)}{activeDistribution.beneficiaries.length === 0 ? <Placeholder>Chưa có người được chỉ định.</Placeholder> : null}</div></div><Question title="Danh sách người được chỉ định đã đầy đủ?" onLaw={() => setRuleId("R-I02")}><BooleanChoice value={activeDistribution.complete} onChange={(complete) => updateDistribution({ complete })} /></Question></CardContent></Card> : <Empty text="Thêm một nhóm định đoạt để bắt đầu." />}</section>
      <Result title={run ? `${distributions.length} nhóm đã đánh giá` : "Chưa chạy CLIPS"} error={error}>{run ? distributions.map((group) => { const result = results.get(`equal-testamentary-share-principle-applies:${group.id}`); const missing = run.missing.filter((item) => item.subject === group.id); return <div key={group.id} className="rounded-xl border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">{group.label}</p><ShareBadge value={result?.value} /></div><p className="mt-2 text-xs text-muted-foreground">{group.beneficiaries.map((item) => item.name).join(" · ") || "Chưa có người hưởng"}</p>{result?.value === "unknown" ? <p className="mt-2 text-xs text-amber-800">Thiếu: {missing.map((item) => missingLabel(item.predicate)).join("; ") || "dữ kiện chưa khớp"}</p> : null}{result?.derivations.includes("R-I02") ? <Button size="sm" variant="ghost" className="mt-2 h-7 px-0 text-xs" onClick={() => setRuleId("R-I02")}>R-I02 · Điều 659 khoản 1</Button> : null}</div>; }) : <Placeholder>CLIPS sẽ đánh giá riêng từng nhóm.</Placeholder>}</Result>
    </main> : mode === "prenatal" ? <main className="mx-auto grid max-w-[1500px] gap-5 p-4 sm:p-6 xl:grid-cols-[300px_minmax(0,1fr)_420px]">
      <aside><Card><CardHeader><CardTitle>Ứng viên từ graph</CardTitle><CardDescription>Hàng của người đang xét được CLIPS suy ra từ quan hệ, không nhập tại đây.</CardDescription></CardHeader><CardContent className="space-y-2">{prenatal.map((item) => <Entity key={item.id} active={item.id === prenatalId} title={item.name} detail={item.assessed ? "Đang đánh giá R-I03" : "Chưa đưa vào đánh giá"} onClick={() => setPrenatalId(item.id)} />)}{prenatal.length === 0 ? <div className="space-y-3"><Placeholder>Graph chưa có ứng viên hàng thừa kế.</Placeholder><Button asChild variant="outline"><Link href={`/cases/${initialCase.id}/modules/heir-rank`}>Mở graph quan hệ</Link></Button></div> : null}</CardContent></Card></aside>
      <section>{activePrenatal ? <Card><CardHeader><div className="flex items-center justify-between gap-2"><Badge variant="outline">{activePrenatal.name}</Badge><Button size="sm" variant={activePrenatal.assessed ? "secondary" : "default"} onClick={() => updatePrenatal({ assessed: !activePrenatal.assessed, conceivedNotBorn: !activePrenatal.assessed ? activePrenatal.conceivedNotBorn : false, outcome: undefined })}>{activePrenatal.assessed ? "Bỏ đánh giá" : "Đánh giá người này"}</Button></div><CardTitle>Dành suất cho người đã thành thai</CardTitle><CardDescription>R-I03a đối chiếu hàng ứng viên từ graph với hàng thừa kế đang hoạt động.</CardDescription></CardHeader>{activePrenatal.assessed ? <CardContent className="space-y-6"><Question rule="R-I03a" title="Tại thời điểm phân chia, người này đã thành thai nhưng chưa sinh?" onLaw={() => setRuleId("R-I03a")}><Choice selected={activePrenatal.conceivedNotBorn} onClick={() => updatePrenatal({ conceivedNotBorn: true })}>Đã thành thai và chưa sinh</Choice></Question><Question rule="R-I03b" title="Kết quả sinh đã được ghi nhận?" onLaw={() => setRuleId("R-I03b")}><div className="grid gap-2 sm:grid-cols-3"><Choice selected={activePrenatal.outcome === undefined} onClick={() => updatePrenatal({ outcome: undefined })}>Chưa có kết quả</Choice><Choice selected={activePrenatal.outcome === "born-alive"} onClick={() => updatePrenatal({ outcome: "born-alive" })}>Sinh ra còn sống</Choice><Choice selected={activePrenatal.outcome === "died-before-birth"} onClick={() => updatePrenatal({ outcome: "died-before-birth" })}>Chết trước khi sinh</Choice></div></Question><p className="rounded-lg bg-sky-50 p-3 text-xs text-sky-900">Muốn thay đổi quan hệ hoặc hoàn tất tìm hàng thừa kế, hãy sửa tại graph. Mô-đun này chỉ ghi nhận sự kiện thai/sinh.</p></CardContent> : null}</Card> : <Empty text="Chọn một ứng viên từ graph." />}</section>
      <Result title={run ? `${prenatal.filter((item) => item.assessed).length} người đã đánh giá` : "Chưa chạy CLIPS"} error={error}>{run ? prenatal.filter((item) => item.assessed).map((person) => { const reserve = results.get(`reserve-equal-share:${person.id}`); const vests = results.get(`reserved-share-vests-in-child:${person.id}`); const returns = results.get(`reserved-share-returns-to-other-heirs:${person.id}`); const missing = run.missing.filter((item) => item.subject === person.id); return <div key={person.id} className="rounded-xl border p-3"><div className="flex items-center justify-between gap-2"><p className="font-semibold">{person.name}</p><Badge variant={reserve?.value === "true" ? "success" : "warning"}>{reserve?.value === "true" ? "Phải dành một suất" : "Chưa đủ dữ kiện"}</Badge></div>{vests ? <p className="mt-2 text-sm text-emerald-800">Sinh ra còn sống: người này hưởng suất đã dành.</p> : null}{returns ? <p className="mt-2 text-sm text-amber-800">Chết trước khi sinh: những người thừa kế khác hưởng suất đã dành.</p> : null}{reserve?.value === "unknown" ? <p className="mt-2 text-xs text-amber-800">Thiếu: {missing.map((item) => missingLabel(item.predicate)).join("; ")}</p> : null}<div className="mt-2 flex gap-2"><Button size="sm" variant="ghost" className="h-7 px-0 text-xs" onClick={() => setRuleId("R-I03a")}>R-I03a · Điều 660</Button>{vests || returns ? <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={() => setRuleId("R-I03b")}>R-I03b · hậu quả</Button> : null}</div></div>; }) : <Placeholder>CLIPS sẽ kết hợp graph, hàng đang hoạt động và trạng thái thai.</Placeholder>}</Result>
    </main> : <RestrictionPanel caseId={initialCase.id} restrictions={restrictions} activeRestriction={activeRestriction} restrictionId={restrictionId} hardships={hardships} activeHardship={activeHardship} hardshipId={hardshipId} run={run} results={results} error={error} onAddRestriction={addRestriction} onUpdateRestriction={updateRestriction} onRemoveRestriction={removeRestriction} onSelectRestriction={setRestrictionId} onUpdateHardship={updateHardship} onSelectHardship={setHardshipId} onLaw={setRuleId} />}

    <div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-3 px-4 pb-8 sm:px-6"><details><summary className="cursor-pointer text-xs font-medium text-muted-foreground">Xem {facts.length} facts Nhóm I</summary><div className="mt-3 max-h-52 overflow-auto rounded-lg bg-slate-950 p-3 text-[11px] text-slate-100">{facts.map((fact) => <code key={fact.id} className="block">{fact.predicate}({fact.subject}, {String(fact.value)})</code>)}</div></details><Button disabled={pending || facts.length === 0} onClick={infer}>{pending ? "CLIPS đang suy luận…" : "Lưu và chạy Nhóm I"}</Button></div>
    <footer className="px-6 pb-8 text-center text-xs text-muted-foreground">Prototype học tập · Không phải tư vấn pháp lý · Knowledge base chưa được phê duyệt chuyên môn</footer><LegalRuleDialog ruleId={ruleId} onOpenChange={(open) => { if (!open) setRuleId(undefined); }} />
  </div>;
}

interface RestrictionPanelProps { caseId: string; restrictions: DivisionRestriction[]; activeRestriction?: DivisionRestriction; restrictionId?: string; hardships: HardshipAssessment[]; activeHardship?: HardshipAssessment; hardshipId?: string; run?: InferenceRun; results: Map<string, InferenceRun["results"][number]>; error?: string; onAddRestriction: () => void; onUpdateRestriction: (value: Partial<DivisionRestriction>) => void; onRemoveRestriction: () => void; onSelectRestriction: (id: string) => void; onUpdateHardship: (value: Partial<HardshipAssessment>) => void; onSelectHardship: (id: string) => void; onLaw: (id: string) => void }
function RestrictionPanel({ caseId, restrictions, activeRestriction, restrictionId, hardships, activeHardship, hardshipId, run, results, error, onAddRestriction, onUpdateRestriction, onRemoveRestriction, onSelectRestriction, onUpdateHardship, onSelectHardship, onLaw }: RestrictionPanelProps) {
  return <main className="mx-auto grid max-w-[1500px] gap-5 p-4 sm:p-6 xl:grid-cols-[300px_minmax(0,1fr)_420px]">
    <aside className="space-y-4"><ListCard title="Mốc hạn chế" description="Theo di chúc hoặc thỏa thuận của tất cả người thừa kế." action="Thêm mốc" empty={restrictions.length === 0} onAdd={onAddRestriction}>{restrictions.map((item) => <Entity key={item.id} active={item.id === restrictionId} title={item.date || "Chưa chọn ngày"} detail={item.basis === "will-instruction" ? "Ý chí trong di chúc" : item.basis === "all-heirs-agreement" ? "Thỏa thuận tất cả người thừa kế" : "Chưa chọn căn cứ"} onClick={() => onSelectRestriction(item.id)} />)}</ListCard><Card><CardHeader><CardTitle>Vợ/chồng từ graph</CardTitle><CardDescription>R-I05 chỉ xuất hiện cho quan hệ phối ngẫu và trạng thái còn sống đã ghi nhận.</CardDescription></CardHeader><CardContent className="space-y-2">{hardships.map((item) => <Entity key={item.id} active={item.id === hardshipId} title={item.name} detail={item.assessed ? "Đang đánh giá khó khăn" : "Chưa đưa vào đánh giá"} onClick={() => onSelectHardship(item.id)} />)}{hardships.length === 0 ? <Button asChild variant="outline"><Link href={`/cases/${caseId}/modules/heir-rank`}>Mở graph quan hệ</Link></Button> : null}</CardContent></Card></aside>
    <section className="space-y-4">{activeRestriction ? <Card><CardHeader><div className="flex justify-between"><Badge variant="outline">R-I04</Badge><Button size="sm" variant="ghost" onClick={onRemoveRestriction}>Xóa mốc</Button></div><CardTitle>Thời điểm sớm nhất được phân chia</CardTitle><CardDescription>Kết quả là một mốc ngày, không phải Boolean “đang bị hạn chế”.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="grid gap-2 sm:grid-cols-2"><Choice selected={activeRestriction.basis === "will-instruction"} onClick={() => onUpdateRestriction({ basis: "will-instruction", allHeirsAgreed: undefined })}>Ý chí trong di chúc</Choice><Choice selected={activeRestriction.basis === "all-heirs-agreement"} onClick={() => onUpdateRestriction({ basis: "all-heirs-agreement" })}>Thỏa thuận người thừa kế</Choice></div>{activeRestriction.basis === "all-heirs-agreement" ? <Question rule="R-I04" title="Tất cả người thừa kế đã cùng thỏa thuận?" onLaw={() => onLaw("R-I04")}><BooleanChoice value={activeRestriction.allHeirsAgreed} onChange={(allHeirsAgreed) => onUpdateRestriction({ allHeirsAgreed })} /></Question> : null}<label className="block text-sm font-medium">Ngày được phép bắt đầu chia<Input className="mt-2" type="date" value={activeRestriction.date ?? ""} onChange={(event) => onUpdateRestriction({ date: event.target.value || undefined })} /></label><Button size="sm" variant="ghost" onClick={() => onLaw("R-I04")}>R-I04 · Điều 661</Button></CardContent></Card> : <Empty text="Thêm mốc hạn chế nếu hồ sơ có di chúc hoặc thỏa thuận tương ứng." />}
      {activeHardship ? <Card><CardHeader><div className="flex items-center justify-between"><Badge variant="warning">R-I05 · TEAM_REVIEW</Badge><Button size="sm" variant={activeHardship.assessed ? "secondary" : "default"} onClick={() => onUpdateHardship({ assessed: !activeHardship.assessed, divisionRequested: undefined, seriousImpact: undefined, priorExpired: undefined, impactStillExists: undefined })}>{activeHardship.assessed ? "Bỏ đánh giá" : "Đánh giá người này"}</Button></div><CardTitle>Quyền yêu cầu Tòa án hoãn chia</CardTitle><CardDescription>Engine không kết luận Tòa đã cho hoãn.</CardDescription></CardHeader>{activeHardship.assessed ? <CardContent className="space-y-5"><Question rule="R-I05" title="Có yêu cầu chia di sản?" onLaw={() => onLaw("R-I05")}><BooleanChoice value={activeHardship.divisionRequested} onChange={(divisionRequested) => onUpdateHardship({ divisionRequested })} /></Question><Question rule="R-I05" title="Việc chia ảnh hưởng nghiêm trọng đến đời sống bên còn sống và gia đình?" onLaw={() => onLaw("R-I05")}><BooleanChoice value={activeHardship.seriousImpact} onChange={(seriousImpact) => onUpdateHardship({ seriousImpact })} /></Question><Question rule="R-I05" title="Thời hạn hoãn lần đầu đã hết?" onLaw={() => onLaw("R-I05")}><BooleanChoice value={activeHardship.priorExpired} onChange={(priorExpired) => onUpdateHardship({ priorExpired, impactStillExists: priorExpired ? activeHardship.impactStillExists : undefined })} /></Question>{activeHardship.priorExpired ? <Question rule="R-I05" title="Ảnh hưởng nghiêm trọng vẫn còn?" onLaw={() => onLaw("R-I05")}><BooleanChoice value={activeHardship.impactStillExists} onChange={(impactStillExists) => onUpdateHardship({ impactStillExists })} /></Question> : null}</CardContent> : null}</Card> : null}</section>
    <Result title={run ? "Kết quả hạn chế phân chia" : "Chưa chạy CLIPS"} error={error}>{run ? <>{restrictions.map((item) => { const result = results.get(`distribution-not-before:${item.id}`); return <div key={item.id} className="rounded-xl border p-3"><p className="font-semibold">Mốc phân chia</p><p className="mt-1 text-lg font-semibold text-primary">{result?.value === "unknown" || !result ? "Chưa đủ dữ kiện" : `Không trước ${result.value}`}</p><Button size="sm" variant="ghost" className="px-0" onClick={() => onLaw("R-I04")}>Xem Điều 661</Button></div>; })}{hardships.filter((item) => item.assessed).map((item) => { const allowed = results.get(`court-deferral-may-be-requested:${item.id}`); const extension = results.get(`court-extension-may-be-requested:${item.id}`); return <div key={item.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><p className="font-semibold">{item.name}</p><Badge variant={allowed?.value === "true" ? "success" : "warning"}>{allowed?.value === "true" ? "Có quyền yêu cầu" : "Chưa đủ dữ kiện"}</Badge></div>{allowed?.value === "true" ? <p className="mt-2 text-sm">Lần đầu: tối đa 3 năm từ thời điểm mở thừa kế.</p> : null}{extension?.value === "true" ? <p className="mt-1 text-sm">Có thể yêu cầu gia hạn một lần, tối đa 3 năm.</p> : null}<p className="mt-2 text-xs text-amber-900">Đây không phải quyết định chấp thuận của Tòa án.</p><Button size="sm" variant="ghost" className="px-0" onClick={() => onLaw("R-I05")}>R-I05 · căn cứ</Button></div>; })}</> : <Placeholder>R-I04 trả mốc ngày; R-I05 chỉ trả quyền yêu cầu và giới hạn thời hạn.</Placeholder>}</Result>
  </main>;
}

function ListCard({ title, description, action, empty, onAdd, children }: { title: string; description: string; action: string; empty: boolean; onAdd: () => void; children: ReactNode }) { return <aside><Card><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle>{title}</CardTitle><Button size="sm" onClick={onAdd}>{action}</Button></div><CardDescription>{description}</CardDescription></CardHeader><CardContent className="space-y-2">{empty ? <button type="button" onClick={onAdd} className="grid min-h-28 w-full place-items-center rounded-xl border border-dashed text-sm text-muted-foreground">+ Tạo mục đầu tiên</button> : children}</CardContent></Card></aside>; }
function Entity({ active, title, detail, onClick }: { active: boolean; title: string; detail: string; onClick: () => void }) { return <button type="button" onClick={onClick} className={cn("w-full rounded-lg border p-3 text-left", active && "border-primary bg-primary/[0.05]")}><span className="block font-semibold">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{detail}</span></button>; }
function Result({ title, error, children }: { title: string; error?: string; children: ReactNode }) { return <aside><Card className="sticky top-4"><CardHeader><Badge variant="outline">Kết quả Nhóm I</Badge><CardTitle>{title}</CardTitle><CardDescription>Kết quả theo từng thực thể, chưa phân bổ tiền end-to-end.</CardDescription></CardHeader><CardContent className="space-y-3">{error ? <p className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}{children}</CardContent></Card></aside>; }
function Question({ title, rule = "R-I02", onLaw, children }: { title: string; rule?: string; onLaw: () => void; children: ReactNode }) { return <div><div className="flex items-center justify-between gap-2"><p className="text-sm font-medium">{title}</p><Button size="sm" variant="ghost" onClick={onLaw}>{rule} · căn cứ</Button></div><div className="mt-2">{children}</div></div>; }
function BooleanChoice({ value, onChange }: { value?: boolean; onChange: (value: boolean) => void }) { return <div className="grid gap-2 sm:grid-cols-2"><Choice selected={value === true} onClick={() => onChange(true)}>Có</Choice><Choice selected={value === false} onClick={() => onChange(false)}>Không</Choice></div>; }
function Choice({ selected, onClick, children }: { selected: boolean; onClick: () => void; children: ReactNode }) { return <button type="button" aria-pressed={selected} onClick={onClick} className={cn("rounded-lg border p-3 text-left text-sm font-medium", selected && "border-primary bg-primary/[0.06] ring-1 ring-primary")}>{children}</button>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-medium">{label}<Input className="mt-2" value={value} maxLength={200} onChange={(event) => onChange(event.target.value)} /></label>; }
function ShareBadge({ value }: { value?: string }) { return <Badge variant={value === "true" ? "success" : value === "false" ? "secondary" : "warning"}>{value === "true" ? "Áp dụng chia đều" : value === "false" ? "Không áp dụng mặc định" : "Chưa đủ dữ kiện"}</Badge>; }
function Placeholder({ children }: { children: ReactNode }) { return <div className="grid min-h-24 place-items-center rounded-xl border border-dashed px-4 text-center text-sm text-muted-foreground">{children}</div>; }
function Empty({ text }: { text: string }) { return <Card><CardHeader><CardTitle>Chưa có dữ liệu</CardTitle><CardDescription>{text}</CardDescription></CardHeader></Card>; }

function restoreObligations(facts: ApiFact[]): Obligation[] { return facts.flatMap((fact): Obligation[] => fact.predicate === "estate-obligation" && fact.value === true && fact.subject ? [{ id: fact.subject, label: String(find(facts, fact.subject, "obligation-label") ?? fact.subject), type: find(facts, fact.subject, "obligation-type") as ObligationType | undefined, amount: find(facts, fact.subject, "obligation-amount") as number | undefined }] : []); }
function restoreDistributions(facts: ApiFact[]): Distribution[] { return facts.flatMap((fact): Distribution[] => fact.predicate === "testamentary-distribution-group" && fact.value === true && fact.subject ? [{ id: fact.subject, label: String(find(facts, fact.subject, "distribution-group-label") ?? fact.subject), beneficiaries: facts.filter((item) => item.subject === fact.subject && item.predicate === "distribution-beneficiary").map((item) => ({ id: String(item.value), name: String(find(facts, String(item.value), "distribution-beneficiary-label") ?? item.value) })), complete: bool(find(facts, fact.subject, "distribution-beneficiary-set-complete")), sharesSpecified: bool(find(facts, fact.subject, "testamentary-shares-specified")), alternativeAgreement: bool(find(facts, fact.subject, "alternative-share-agreement")) }] : []); }
function restorePrenatalAssessments(facts: ApiFact[]): PrenatalAssessment[] { const ids = [...new Set(facts.flatMap((fact) => (fact.predicate === "heir-rank-candidate" || fact.predicate === "prenatal-share-assessment-subject") && fact.subject ? [fact.subject] : []))]; return ids.map((id) => ({ id, name: String(find(facts, id, "heir-person-label") ?? find(facts, id, "person-label") ?? id), assessed: find(facts, id, "prenatal-share-assessment-subject") === true, conceivedNotBorn: find(facts, id, "prenatal-status-at-distribution") === "conceived-not-born", outcome: find(facts, id, "prenatal-birth-outcome") as PrenatalAssessment["outcome"] })); }
function restoreRestrictions(facts: ApiFact[]): DivisionRestriction[] { return facts.flatMap((fact): DivisionRestriction[] => fact.predicate === "division-restriction-assessment-subject" && fact.value === true && fact.subject ? [{ id: fact.subject, basis: find(facts, fact.subject, "division-restriction-basis") as DivisionRestriction["basis"], allHeirsAgreed: bool(find(facts, fact.subject, "all-heirs-agreed")), date: find(facts, fact.subject, "specified-division-date") as string | undefined }] : []); }
function restoreHardships(facts: ApiFact[]): HardshipAssessment[] { const deceased = new Set(facts.filter((fact) => fact.predicate === "deceased-person" && fact.value === true).map((fact) => fact.subject)); const spouseIds = new Set(facts.flatMap((fact) => fact.predicate === "spouse-at-opening" && fact.subject && typeof fact.value === "string" ? deceased.has(fact.subject) ? [fact.value] : deceased.has(fact.value) ? [fact.subject] : [] : [])); facts.filter((fact) => fact.predicate === "division-hardship-assessment-subject" && fact.subject).forEach((fact) => spouseIds.add(fact.subject!)); return [...spouseIds].map((id) => ({ id, name: String(find(facts, id, "heir-person-label") ?? find(facts, id, "person-label") ?? id), assessed: find(facts, id, "division-hardship-assessment-subject") === true, divisionRequested: bool(find(facts, id, "estate-division-requested")), seriousImpact: bool(find(facts, id, "serious-division-impact")), priorExpired: bool(find(facts, id, "prior-court-deferral-expired")), impactStillExists: bool(find(facts, id, "serious-impact-still-exists")) })); }
function obligationFacts(items: Obligation[]): ApiFact[] { return items.flatMap((item): ApiFact[] => { const facts: ApiFact[] = [{ id: `${item.id}-entity`, subject: item.id, predicate: "estate-obligation", value: true }, { id: `${item.id}-label`, subject: item.id, predicate: "obligation-label", value: item.label || item.id }]; if (item.type) facts.push({ id: `${item.id}-type`, subject: item.id, predicate: "obligation-type", value: item.type }); if (item.amount !== undefined) facts.push({ id: `${item.id}-amount`, subject: item.id, predicate: "obligation-amount", value: item.amount }); return facts; }); }
function distributionFacts(items: Distribution[]): ApiFact[] { return items.flatMap((group): ApiFact[] => { const facts: ApiFact[] = [{ id: `${group.id}-entity`, subject: group.id, predicate: "testamentary-distribution-group", value: true }, { id: `${group.id}-label`, subject: group.id, predicate: "distribution-group-label", value: group.label || group.id }]; group.beneficiaries.forEach((person, index) => facts.push({ id: `${group.id}-beneficiary-${index}`, subject: group.id, predicate: "distribution-beneficiary", value: person.id }, { id: `${person.id}-distribution-label`, subject: person.id, predicate: "distribution-beneficiary-label", value: person.name || person.id })); if (group.complete !== undefined) facts.push({ id: `${group.id}-complete`, subject: group.id, predicate: "distribution-beneficiary-set-complete", value: group.complete }); if (group.sharesSpecified !== undefined) facts.push({ id: `${group.id}-shares`, subject: group.id, predicate: "testamentary-shares-specified", value: group.sharesSpecified }); if (group.alternativeAgreement !== undefined) facts.push({ id: `${group.id}-agreement`, subject: group.id, predicate: "alternative-share-agreement", value: group.alternativeAgreement }); return facts; }); }
function prenatalFacts(items: PrenatalAssessment[]): ApiFact[] { return items.flatMap((item): ApiFact[] => { if (!item.assessed) return []; const facts: ApiFact[] = [{ id: `${item.id}-prenatal-scope`, subject: item.id, predicate: "prenatal-share-assessment-subject", value: true }]; if (item.conceivedNotBorn) facts.push({ id: `${item.id}-prenatal-status`, subject: item.id, predicate: "prenatal-status-at-distribution", value: "conceived-not-born" }); if (item.outcome) facts.push({ id: `${item.id}-prenatal-outcome`, subject: item.id, predicate: "prenatal-birth-outcome", value: item.outcome }); return facts; }); }
function restrictionFacts(items: DivisionRestriction[]): ApiFact[] { return items.flatMap((item): ApiFact[] => { const facts: ApiFact[] = [{ id: `${item.id}-scope`, subject: item.id, predicate: "division-restriction-assessment-subject", value: true }]; if (item.basis) facts.push({ id: `${item.id}-basis`, subject: item.id, predicate: "division-restriction-basis", value: item.basis }); if (item.basis === "all-heirs-agreement" && item.allHeirsAgreed !== undefined) facts.push({ id: `${item.id}-agreement`, subject: item.id, predicate: "all-heirs-agreed", value: item.allHeirsAgreed }); if (item.date) facts.push({ id: `${item.id}-date`, subject: item.id, predicate: "specified-division-date", value: item.date }); return facts; }); }
function hardshipFacts(items: HardshipAssessment[]): ApiFact[] { return items.flatMap((item): ApiFact[] => { if (!item.assessed) return []; const facts: ApiFact[] = [{ id: `${item.id}-hardship-scope`, subject: item.id, predicate: "division-hardship-assessment-subject", value: true }]; if (item.divisionRequested !== undefined) facts.push({ id: `${item.id}-division-request`, subject: item.id, predicate: "estate-division-requested", value: item.divisionRequested }); if (item.seriousImpact !== undefined) facts.push({ id: `${item.id}-serious-impact`, subject: item.id, predicate: "serious-division-impact", value: item.seriousImpact }); if (item.priorExpired !== undefined) facts.push({ id: `${item.id}-prior-expired`, subject: item.id, predicate: "prior-court-deferral-expired", value: item.priorExpired }); if (item.priorExpired && item.impactStillExists !== undefined) facts.push({ id: `${item.id}-impact-still`, subject: item.id, predicate: "serious-impact-still-exists", value: item.impactStillExists }); return facts; }); }
function find(facts: ApiFact[], subject: string, predicate: string) { return facts.find((fact) => fact.subject === subject && fact.predicate === predicate)?.value; }
function bool(value: ApiFact["value"] | undefined): boolean | undefined { return typeof value === "boolean" ? value : undefined; }
function priorityOf(value?: string): number | undefined { const number = Number(value); return Number.isInteger(number) && number >= 1 ? number : undefined; }
function uid(prefix: string) { return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`; }
function missingLabel(predicate: string) { return ({ "distribution-beneficiary-set-complete": "xác nhận danh sách đầy đủ", "distribution-beneficiary": "người được chỉ định", "testamentary-shares-specified": "di chúc có xác định phần", "alternative-share-agreement": "thỏa thuận chia khác", "prenatal-status-at-distribution": "trạng thái đã thành thai/chưa sinh", "candidate-heir-rank": "quan hệ để suy ra hàng", "active-heir-rank": "hàng thừa kế đang hoạt động" } as Record<string, string>)[predicate] ?? predicate; }
async function json<T = unknown>(url: string, init: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "content-type": "application/json", ...init.headers } }); const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error ?? `Request thất bại (${response.status}).`); return data; }
