"use client";

import { useMemo, useState, useTransition } from "react";
import { LegalRuleDialog } from "@/components/inference/legal-rule-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { GuidedCaseState } from "@/domain/guided-conversation";
import { cn } from "@/lib/utils";
import type { ApiFact } from "@/modules/contracts";

type Mode = "restriction" | "hardship";
type RestrictionBasis = "will-instruction" | "all-heirs-agreement";
interface Draft { mode?: Mode; basis?: RestrictionBasis; date: string; spouseId: string; spouseName: string; divisionRequested?: boolean; seriousImpact?: boolean; priorExpired?: boolean; impactStillExists?: boolean }

export function GuidedDivisionTimelineStep({ state, onStateChange }: { state: GuidedCaseState; onStateChange: (state: GuidedCaseState) => void }) {
  const deceasedId = state.case.facts.find((fact) => fact.predicate === "deceased-person" && fact.value === true)?.subject;
  const spouses = useMemo(() => spouseOptions(state.case.facts, deceasedId), [state.case.facts, deceasedId]);
  const [draft, setDraft] = useState<Draft>(() => restore(state.case.facts, spouses[0]));
  const [ruleId, setRuleId] = useState<string>();
  const [error, setError] = useState<string>();
  const [pending, startTransition] = useTransition();
  const ready = draft.mode === "restriction" ? Boolean(draft.basis && draft.date) : draft.mode === "hardship" && Boolean(draft.spouseName.trim()) && draft.divisionRequested !== undefined && draft.seriousImpact !== undefined && (draft.priorExpired !== true || draft.impactStillExists !== undefined);
  const update = (change: Partial<Draft>) => setDraft((current) => ({ ...current, ...change }));

  function save() {
    if (!ready || !deceasedId) return;
    startTransition(async () => {
      setError(undefined);
      try {
        const retained = state.case.facts.filter((fact) => !fact.id.startsWith("gdt-"));
        await json(`/api/cases/${state.case.id}/facts`, { method: "PUT", body: JSON.stringify({ subject: state.case.id, facts: [...retained, ...factsFor(draft, deceasedId)] }) });
        onStateChange(await json<GuidedCaseState>(`/api/cases/${state.case.id}/guided/inference`, { method: "POST", body: "{}" }));
      } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể lưu dữ kiện Điều 661."); }
    });
  }

  return <Card className="max-w-3xl"><CardHeader><Badge variant="outline" className="w-fit">Điều 661 · Mốc phân chia</Badge><CardTitle className="text-lg">Vấn đề hạn chế phân chia thuộc trường hợp nào?</CardTitle><CardDescription>Chọn một trong hai trường hợp: mốc chưa được chia theo khoản 1, hoặc quyền yêu cầu Tòa án trì hoãn theo khoản 2.</CardDescription></CardHeader><CardContent className="space-y-6">
    <div className="grid gap-3 sm:grid-cols-2"><Choice selected={draft.mode === "restriction"} onClick={() => update({ mode: "restriction" })}><strong className="block">Có mốc chưa được chia</strong><span className="mt-1 block font-normal text-muted-foreground">Theo ý chí người lập di chúc hoặc thỏa thuận của tất cả người thừa kế.</span></Choice><Choice selected={draft.mode === "hardship"} onClick={() => update({ mode: "hardship" })}><strong className="block">Vợ/chồng xin trì hoãn chia</strong><span className="mt-1 block font-normal text-muted-foreground">Việc chia có thể ảnh hưởng nghiêm trọng đến đời sống.</span></Choice></div>
    {draft.mode === "restriction" ? <div className="space-y-5"><div><p className="text-sm font-medium">Căn cứ xác lập thời hạn</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><Choice selected={draft.basis === "will-instruction"} onClick={() => update({ basis: "will-instruction" })}>Ý chí của người lập di chúc</Choice><Choice selected={draft.basis === "all-heirs-agreement"} onClick={() => update({ basis: "all-heirs-agreement" })}>Tất cả người thừa kế đã thỏa thuận</Choice></div></div><label className="block text-sm font-medium">Không được phân chia trước ngày<Input className="mt-2" type="date" value={draft.date} onChange={(event) => update({ date: event.target.value })} /></label></div> : null}
    {draft.mode === "hardship" ? <div className="space-y-5"><div><p className="text-sm font-medium">Người vợ/chồng còn sống cần đánh giá</p>{spouses.length ? <div className="mt-2 flex flex-wrap gap-2">{spouses.map((person) => <Button key={person.id} type="button" size="sm" variant={draft.spouseId === person.id ? "secondary" : "outline"} onClick={() => update({ spouseId: person.id, spouseName: person.name })}>{person.name}</Button>)}</div> : null}<Input className="mt-2" value={draft.spouseName} placeholder="Tên người vợ/chồng" onChange={(event) => update({ spouseId: draft.spouseId || "spouse-guided", spouseName: event.target.value })} /></div><BooleanQuestion label="Đã có yêu cầu chia di sản?" value={draft.divisionRequested} onChange={(divisionRequested) => update({ divisionRequested })} /><BooleanQuestion label="Nếu chia ngay, đời sống của người này và gia đình bị ảnh hưởng nghiêm trọng?" value={draft.seriousImpact} onChange={(seriousImpact) => update({ seriousImpact })} /><BooleanQuestion label="Thời hạn trì hoãn do Tòa án quyết định trước đó đã hết?" value={draft.priorExpired} onChange={(priorExpired) => update({ priorExpired, impactStillExists: priorExpired ? draft.impactStillExists : undefined })} />{draft.priorExpired ? <BooleanQuestion label="Ảnh hưởng nghiêm trọng vẫn còn tồn tại?" value={draft.impactStillExists} onChange={(impactStillExists) => update({ impactStillExists })} /> : null}</div> : null}
    <div className="flex flex-wrap items-center justify-between gap-3"><Button variant="ghost" className="px-0" onClick={() => setRuleId(draft.mode === "hardship" ? "R-I05" : "R-I04")}>Đọc căn cứ Điều 661</Button><Button disabled={!ready || pending || !deceasedId} onClick={save}>{pending ? "Đang suy luận timeline…" : "Lưu và tiếp tục"}</Button></div>
    {error ? <p className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}
  </CardContent><LegalRuleDialog ruleId={ruleId} onOpenChange={(open) => { if (!open) setRuleId(undefined); }} /></Card>;
}

function BooleanQuestion({ label, value, onChange }: { label: string; value?: boolean; onChange: (value: boolean) => void }) { return <div><p className="text-sm font-medium">{label}</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><Choice selected={value === true} onClick={() => onChange(true)}>Có</Choice><Choice selected={value === false} onClick={() => onChange(false)}>Không</Choice></div></div>; }
function Choice({ selected, onClick, children }: { selected: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" aria-pressed={selected} onClick={onClick} className={cn("rounded-xl border p-4 text-left text-sm font-medium outline-none transition hover:border-primary/60 focus-visible:ring-2 focus-visible:ring-ring", selected && "border-primary bg-primary/[0.06] ring-1 ring-primary")}>{children}</button>; }
function spouseOptions(facts: readonly ApiFact[], deceasedId?: string): Array<{ id: string; name: string }> { if (!deceasedId) return []; const ids = [...new Set(facts.flatMap((fact) => fact.predicate === "spouse-at-opening" && typeof fact.value === "string" ? fact.subject === deceasedId ? [fact.value] : fact.value === deceasedId && fact.subject ? [fact.subject] : [] : []))]; return ids.map((id) => ({ id, name: String(facts.find((fact) => fact.subject === id && (fact.predicate === "heir-person-label" || fact.predicate === "person-label"))?.value ?? id) })); }
function restore(facts: readonly ApiFact[], spouse?: { id: string; name: string }): Draft { const restriction = facts.find((fact) => fact.predicate === "division-restriction-assessment-subject" && fact.value === true)?.subject; const hardship = facts.find((fact) => fact.predicate === "division-hardship-assessment-subject" && fact.value === true)?.subject; const bool = (subject: string | undefined, predicate: string) => facts.find((fact) => fact.subject === subject && fact.predicate === predicate)?.value as boolean | undefined; return { mode: restriction ? "restriction" : hardship ? "hardship" : undefined, basis: facts.find((fact) => fact.subject === restriction && fact.predicate === "division-restriction-basis")?.value as RestrictionBasis | undefined, date: String(facts.find((fact) => fact.subject === restriction && fact.predicate === "specified-division-date")?.value ?? ""), spouseId: hardship ?? spouse?.id ?? "spouse-guided", spouseName: String(facts.find((fact) => fact.subject === hardship && (fact.predicate === "heir-person-label" || fact.predicate === "person-label"))?.value ?? spouse?.name ?? ""), divisionRequested: bool(hardship, "estate-division-requested"), seriousImpact: bool(hardship, "serious-division-impact"), priorExpired: bool(hardship, "prior-court-deferral-expired"), impactStillExists: bool(hardship, "serious-impact-still-exists") }; }
function factsFor(draft: Draft, deceasedId: string): ApiFact[] { if (draft.mode === "restriction") return [{ id: "gdt-restriction-scope", subject: "restriction-guided", predicate: "division-restriction-assessment-subject", value: true }, { id: "gdt-restriction-basis", subject: "restriction-guided", predicate: "division-restriction-basis", value: draft.basis! }, ...(draft.basis === "all-heirs-agreement" ? [{ id: "gdt-all-agreed", subject: "restriction-guided", predicate: "all-heirs-agreed", value: true } satisfies ApiFact] : []), { id: "gdt-restriction-date", subject: "restriction-guided", predicate: "specified-division-date", value: draft.date }]; return [{ id: "gdt-hardship-scope", subject: draft.spouseId, predicate: "division-hardship-assessment-subject", value: true }, { id: "gdt-spouse-label", subject: draft.spouseId, predicate: "person-label", value: draft.spouseName.trim() }, { id: "gdt-spouse-edge", subject: deceasedId, predicate: "spouse-at-opening", value: draft.spouseId }, { id: "gdt-spouse-life", subject: draft.spouseId, predicate: "heir-life-status", value: "alive" }, { id: "gdt-requested", subject: draft.spouseId, predicate: "estate-division-requested", value: draft.divisionRequested! }, { id: "gdt-impact", subject: draft.spouseId, predicate: "serious-division-impact", value: draft.seriousImpact! }, ...(draft.priorExpired !== undefined ? [{ id: "gdt-prior-expired", subject: draft.spouseId, predicate: "prior-court-deferral-expired", value: draft.priorExpired } satisfies ApiFact] : []), ...(draft.priorExpired && draft.impactStillExists !== undefined ? [{ id: "gdt-impact-still", subject: draft.spouseId, predicate: "serious-impact-still-exists", value: draft.impactStillExists } satisfies ApiFact] : [])]; }
async function json<T = unknown>(url: string, init: RequestInit): Promise<T> { const response = await fetch(url, { ...init, signal: init.signal ?? AbortSignal.timeout(20_000), headers: { "content-type": "application/json", ...init.headers } }); const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error ?? `Request thất bại (${response.status}).`); return data; }
