; GENERATED FILE — do not edit directly.
; Source: knowledge-base/rule-registry.json
; Run: npm run kb:generate

(deffacts will-validity-rule-metadata
  (rule-metadata
    (rule-id FORM-ASSESSMENT-ACCEPTED)
    (module will-validity)
    (legal-source "Quy tắc chuyển tiếp nội bộ; liên quan Điều 627–636")
    (description "Từ dữ kiện di chúc bằng văn bản và chưa phát hiện khiếm khuyết hình thức, hệ thống tạm ghi nhận điều kiện hình thức đã đạt.")
    (status draft))
  (rule-metadata
    (rule-id R-B01)
    (module will-validity)
    (legal-source "Điều 630 khoản 1 điểm a Bộ luật Dân sự 2015")
    (description "Vì người lập di chúc minh mẫn, sáng suốt và không có dữ kiện về lừa dối hoặc đe dọa, hệ thống suy ra điều kiện về ý chí đã đạt.")
    (status draft))
  (rule-metadata
    (rule-id R-B02)
    (module will-validity)
    (legal-source "Điều 630 khoản 1 điểm b Bộ luật Dân sự 2015")
    (description "Vì không phát hiện nội dung bị cấm và điều kiện hình thức đã đạt, hệ thống suy ra điều kiện về nội dung và hình thức đã đạt.")
    (status draft))
  (rule-metadata
    (rule-id R-B03)
    (module will-validity)
    (legal-source "Điều 630 Bộ luật Dân sự 2015")
    (description "Khi điều kiện về ý chí, nội dung và hình thức đều đã được dẫn xuất là hợp lệ, hệ thống kết luận di chúc hợp pháp.")
    (status draft))
  (rule-metadata
    (rule-id R-B04)
    (module will-validity)
    (legal-source "Điều 630 khoản 1 điểm a Bộ luật Dân sự 2015")
    (description "Trạng thái không minh mẫn hoặc tác động trái ý chí làm điều kiện tại khoản 1 điểm a không được đáp ứng.")
    (status draft))
  (rule-metadata
    (rule-id R-B05)
    (module will-validity)
    (legal-source "Điều 630 khoản 2 Bộ luật Dân sự 2015")
    (description "Độ tuổi, hình thức văn bản và sự đồng ý của cha, mẹ hoặc người giám hộ đáp ứng yêu cầu riêng đối với người chưa thành niên.")
    (status draft))
  (rule-metadata
    (rule-id R-B06)
    (module will-validity)
    (legal-source "Điều 630 khoản 2 Bộ luật Dân sự 2015")
    (description "Người từ 15 đến dưới 18 tuổi không lập di chúc bằng văn bản hoặc không có sự đồng ý cần thiết nên không đạt yêu cầu riêng.")
    (status draft))
  (rule-metadata
    (rule-id R-B07)
    (module will-validity)
    (legal-source "Điều 630 khoản 3 Bộ luật Dân sự 2015")
    (description "Đối với người bị hạn chế thể chất hoặc không biết chữ, văn bản do người làm chứng lập và được công chứng hoặc chứng thực đáp ứng yêu cầu hình thức.")
    (status draft))
  (rule-metadata
    (rule-id R-B08)
    (module will-validity)
    (legal-source "Điều 629 khoản 2 Bộ luật Dân sự 2015")
    (description "Sau ba tháng, người lập vẫn còn sống, minh mẫn và sáng suốt nên di chúc miệng mặc nhiên bị hủy bỏ.")
    (status draft))
  (rule-metadata
    (rule-id R-B09)
    (module will-validity)
    (legal-source "Điều 630 khoản 5 Bộ luật Dân sự 2015")
    (description "Số người làm chứng, việc ghi chép, ký hoặc điểm chỉ và thời hạn xác nhận đáp ứng các điều kiện của di chúc miệng.")
    (status draft))
  (rule-metadata
    (rule-id R-C01)
    (module heir-rank)
    (legal-source "Điều 651 khoản 1 điểm a Bộ luật Dân sự 2015")
    (description "Quan hệ vợ/chồng tại thời điểm mở thừa kế, cha mẹ đẻ hoặc nuôi, và con đẻ hoặc nuôi đặt người đang xét vào nhóm ứng viên hàng thứ nhất. Kết luận này chưa tự động có nghĩa người đó được gọi hưởng.")
    (status draft))
  (rule-metadata
    (rule-id R-C02)
    (module heir-rank)
    (legal-source "Điều 651 khoản 1 điểm b Bộ luật Dân sự 2015")
    (description "Đường quan hệ huyết thống trong graph cho thấy người đang xét là ông/bà, anh/chị/em ruột hoặc cháu ruột mà người chết là ông/bà.")
    (status draft))
  (rule-metadata
    (rule-id R-C03)
    (module heir-rank)
    (legal-source "Điều 651 khoản 1 điểm c Bộ luật Dân sự 2015")
    (description "Đường quan hệ huyết thống trong graph cho thấy người đang xét là cụ, bác/chú/cậu/cô/dì, cháu ruột theo nhánh anh chị em hoặc chắt ruột của người chết.")
    (status draft))
  (rule-metadata
    (rule-id R-C04)
    (module heir-rank)
    (legal-source "Điều 651 khoản 2 Bộ luật Dân sự 2015")
    (description "Khi có từ hai người trở lên cùng được gọi hưởng ở hàng đang hoạt động, hệ thống ghi nhận nguyên tắc cùng hàng hưởng phần bằng nhau; mô-đun này chưa tính giá trị phần chia.")
    (status draft))
  (rule-metadata
    (rule-id R-C05)
    (module heir-rank)
    (legal-source "Điều 651 khoản 3 Bộ luật Dân sự 2015")
    (description "Khi đã xác định có người đủ điều kiện ở một hàng trước, ứng viên thuộc hàng sau chưa được gọi hưởng theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-C06)
    (module heir-rank)
    (legal-source "Điều 651 khoản 3 Bộ luật Dân sự 2015; kết nối Điều 621")
    (description "Chỉ sau khi danh sách ứng viên được xác nhận đầy đủ, hệ thống chọn hàng thấp nhất còn người sống, không từ chối hợp lệ và không bị loại khỏi thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id SYSTEM-RANK-CONFLICT)
    (module heir-rank)
    (legal-source "Quy tắc kiểm soát nhất quán của hệ thống")
    (description "Cùng một người được graph quan hệ dẫn xuất vào nhiều hàng khác nhau.")
    (status draft))
  (rule-metadata
    (rule-id STATUTORY-CANDIDATE-QUALIFIED)
    (module heir-rank)
    (legal-source "Quy tắc kết nối nội bộ giữa Điều 621 và Điều 651")
    (description "Ứng viên đã có hàng, còn sống, không từ chối hợp lệ và không bị loại theo Điều 621.")
    (status draft))
  (rule-metadata
    (rule-id STATUTORY-CANDIDATE-INACTIVE)
    (module heir-rank)
    (legal-source "Quy tắc kết nối nội bộ; liên quan Điều 620, Điều 621 và Điều 651")
    (description "Ứng viên đã chết trước hoặc cùng thời điểm, từ chối hợp lệ, hoặc bị Điều 621 loại khỏi thừa kế theo pháp luật. Ngoại lệ được hưởng theo di chúc không làm người đó đủ điều kiện hưởng theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id STATUTORY-CANDIDATE-UNRESOLVED)
    (module heir-rank)
    (legal-source "Quy tắc completeness nội bộ; phục vụ áp dụng Điều 651 khoản 3")
    (description "Ứng viên đã được xếp hàng nhưng chưa thể chứng minh là đủ điều kiện hoặc bị loại; vì vậy không được xem người ở hàng này là vắng mặt.")
    (status draft))
  (rule-metadata
    (rule-id REPRESENTED-CHILD-WOULD-BE-ENTITLED)
    (module representation)
    (legal-source "Quy tắc kết nối Điều 621, Điều 651 và Điều 652")
    (description "Người được thế vị là con ruột của người để lại di sản, chết trước hoặc cùng thời điểm và không bị loại theo Điều 621.")
    (status draft))
  (rule-metadata
    (rule-id REPRESENTATION-CANDIDATE-QUALIFIED)
    (module representation)
    (legal-source "Quy tắc kết nối nội bộ; liên quan Điều 620–621 và Điều 652")
    (description "Ứng viên còn sống, không từ chối hợp lệ và không bị loại theo Điều 621.")
    (status draft))
  (rule-metadata
    (rule-id REPRESENTED-GRANDCHILD-WOULD-BE-ENTITLED)
    (module representation)
    (legal-source "Quy tắc kết nối Điều 621 và Điều 652")
    (description "Người cháu nằm trong nhánh thế vị hợp lệ của người con đã chết, bản thân cũng chết trước hoặc cùng thời điểm và không bị loại theo Điều 621.")
    (status draft))
  (rule-metadata
    (rule-id R-E01)
    (module representation)
    (legal-source "Điều 652 Bộ luật Dân sự 2015")
    (description "Graph thể hiện người con của người để lại di sản đã chết trước hoặc cùng thời điểm, còn người con của họ đủ điều kiện hưởng phần thế vị.")
    (status draft))
  (rule-metadata
    (rule-id R-E02)
    (module representation)
    (legal-source "Điều 652 Bộ luật Dân sự 2015")
    (description "Graph thể hiện cả người con và người cháu trong nhánh đã chết trước hoặc cùng thời điểm, còn người chắt đủ điều kiện hưởng phần thế vị.")
    (status draft))
  (rule-metadata
    (rule-id R-E03a)
    (module representation)
    (legal-source "Điều 653 Bộ luật Dân sự 2015")
    (description "Cạnh cha/mẹ nuôi–con nuôi hợp pháp tạo căn cứ quan hệ thừa kế theo cả hai chiều. Đây chưa phải kết luận người đó thực tế được hưởng trong vụ việc.")
    (status draft))
  (rule-metadata
    (rule-id R-E03b)
    (module representation)
    (legal-source "Điều 653 Bộ luật Dân sự 2015; đối chiếu Điều 651–652")
    (description "Khi graph có cả cạnh cha/mẹ nuôi và cha/mẹ đẻ tới cùng một người con, hệ thống giữ hai căn cứ độc lập thay vì gộp hoặc loại bỏ một quan hệ.")
    (status draft))
  (rule-metadata
    (rule-id R-E04)
    (module representation)
    (legal-source "Điều 654 Bộ luật Dân sự 2015")
    (description "Quan hệ con riêng–bố dượng hoặc mẹ kế chỉ tạo căn cứ thừa kế hai chiều khi đánh giá gắn với chính quan hệ đó xác nhận có chăm sóc, nuôi dưỡng nhau như cha con, mẹ con. Kết luận này chưa tự động xác định quyền hưởng cuối cùng.")
    (status draft))
  (rule-metadata
    (rule-id R-E05)
    (module representation)
    (legal-source "Suy luận loại trừ cần team review từ Điều 654 Bộ luật Dân sự 2015")
    (description "Chỉ khi có đánh giá tường minh rằng quan hệ con riêng–bố dượng hoặc mẹ kế không có việc chăm sóc, nuôi dưỡng như cha con, mẹ con, hệ thống mới phủ định căn cứ hưởng theo riêng quan hệ đặc biệt này. Thiếu đánh giá không được xem là kết luận phủ định.")
    (status draft))
  (rule-metadata
    (rule-id SYSTEM-STEP-CARE-CONFLICT)
    (module representation)
    (legal-source "Quy tắc kiểm soát nhất quán của hệ thống")
    (description "Cùng một cạnh quan hệ con riêng–bố dượng hoặc mẹ kế vừa được đánh giá có, vừa được đánh giá không có chăm sóc như cha con, mẹ con.")
    (status draft))
  (rule-metadata
    (rule-id R-F01a)
    (module compulsory-share)
    (legal-source "Điều 644 khoản 1 điểm a Bộ luật Dân sự 2015")
    (description "Graph xác định người đang xét là con đẻ hoặc con nuôi của người để lại di sản và dữ kiện tuổi xác định người đó chưa thành niên.")
    (status draft))
  (rule-metadata
    (rule-id R-F01b)
    (module compulsory-share)
    (legal-source "Điều 644 khoản 1 điểm a Bộ luật Dân sự 2015")
    (description "Quan hệ cha mẹ đẻ, cha mẹ nuôi hoặc vợ chồng tại thời điểm mở thừa kế đặt người đang xét vào nhóm đối tượng tại Điều 644 khoản 1 điểm a.")
    (status draft))
  (rule-metadata
    (rule-id R-F01c)
    (module compulsory-share)
    (legal-source "Điều 644 khoản 1 Bộ luật Dân sự 2015")
    (description "Trong một calculation gắn với đúng người và phần di sản, hệ thống lấy hai phần ba suất thừa kế theo pháp luật giả định làm ngưỡng. Nếu phần đã nhận theo di chúc thấp hơn ngưỡng, phần chênh lệch được ghi nhận là phần còn thiếu theo cơ chế Điều 644.")
    (status draft))
  (rule-metadata
    (rule-id R-F02)
    (module compulsory-share)
    (legal-source "Điều 644 khoản 1 điểm b Bộ luật Dân sự 2015")
    (description "Graph xác định quan hệ con, dữ kiện tuổi là thành niên và đánh giá khả năng lao động là không có khả năng lao động.")
    (status draft))
  (rule-metadata
    (rule-id R-F03)
    (module compulsory-share)
    (legal-source "Điều 644 khoản 2; Điều 620 Bộ luật Dân sự 2015")
    (description "Người thuộc nhóm được bảo vệ nhưng đã từ chối nhận di sản hợp lệ thì khoản 1 Điều 644 không áp dụng.")
    (status draft))
  (rule-metadata
    (rule-id R-F04)
    (module compulsory-share)
    (legal-source "Điều 644 khoản 2; Điều 621 khoản 1 Bộ luật Dân sự 2015")
    (description "Người thuộc nhóm được bảo vệ nhưng có kết luận bị loại theo khoản 1 Điều 621 thì khoản 1 Điều 644 không áp dụng.")
    (status draft))
  (rule-metadata
    (rule-id COMPULSORY-HEIR-ACTIVE)
    (module compulsory-share)
    (legal-source "Quy tắc kết nối nội bộ Điều 620, Điều 621 và Điều 644")
    (description "Người thuộc nhóm đối tượng Điều 644, không từ chối hợp lệ và không bị Điều 621 loại trừ được giữ trong tập chờ đối chiếu phần được chỉ định với ngưỡng hai phần ba.")
    (status draft))
  (rule-metadata
    (rule-id COMPULSORY-CANDIDATE-NOT-IN-PROTECTED-CLASS)
    (module compulsory-share)
    (legal-source "Quy tắc completeness phục vụ Điều 644")
    (description "Sau khi graph gia đình đã được xác nhận đầy đủ và các thuộc tính cần thiết đã được đánh giá, người đang xét không khớp nhóm đối tượng tại khoản 1 Điều 644.")
    (status draft))
  (rule-metadata
    (rule-id R-G01)
    (module spouse-status)
    (legal-source "Điều 655 khoản 1 Bộ luật Dân sự 2015")
    (description "Người đang xét là vợ hoặc chồng tại thời điểm mở thừa kế; việc vợ chồng đã chia tài sản chung trong thời kỳ hôn nhân không tự làm mất căn cứ thừa kế của người còn sống.")
    (status draft))
  (rule-metadata
    (rule-id R-G02)
    (module spouse-status)
    (legal-source "Điều 655 khoản 2 Bộ luật Dân sự 2015")
    (description "Tại thời điểm một bên chết, vụ việc ly hôn đang được giải quyết nhưng bản án hoặc quyết định chưa có hiệu lực pháp luật nên người còn sống vẫn được xem xét với tư cách vợ hoặc chồng.")
    (status draft))
  (rule-metadata
    (rule-id R-G03)
    (module spouse-status)
    (legal-source "Điều 655 khoản 3 Bộ luật Dân sự 2015")
    (description "Người đang xét là vợ hoặc chồng tại thời điểm mở thừa kế; việc người đó kết hôn với người khác sau thời điểm này không làm mất căn cứ hưởng di sản đã phát sinh.")
    (status draft))
  (rule-metadata
    (rule-id SPOUSE-STATUS-PRESERVED)
    (module spouse-status)
    (legal-source "Quy tắc kết nối nội bộ Điều 655")
    (description "Ít nhất một hoàn cảnh đặc biệt tại Điều 655 đã được dẫn xuất cho người đang xét.")
    (status draft))
  (rule-metadata
    (rule-id R-H01)
    (module refusal-and-unclaimed)
    (legal-source "Điều 620 khoản 1 Bộ luật Dân sự 2015")
    (description "Người đang xét đã thể hiện việc từ chối và mục đích không nhằm trốn tránh thực hiện nghĩa vụ tài sản đối với người khác.")
    (status draft))
  (rule-metadata
    (rule-id R-H02)
    (module refusal-and-unclaimed)
    (legal-source "Điều 620 khoản 1 Bộ luật Dân sự 2015")
    (description "Việc từ chối đã được thực hiện nhằm trốn tránh nghĩa vụ tài sản đối với người khác nên không đáp ứng khoản 1 Điều 620.")
    (status draft))
  (rule-metadata
    (rule-id R-H03)
    (module refusal-and-unclaimed)
    (legal-source "Điều 620 khoản 2 Bộ luật Dân sự 2015")
    (description "Việc từ chối được lập thành văn bản và gửi đến người quản lý di sản, người thừa kế khác hoặc người được giao nhiệm vụ phân chia di sản.")
    (status draft))
  (rule-metadata
    (rule-id VALID-REFUSAL-COMPOSED)
    (module refusal-and-unclaimed)
    (legal-source "Quy tắc kết nối nội bộ các khoản 1–3 Điều 620")
    (description "Điều kiện nội dung, hình thức/thông báo và thời điểm trước khi phân chia di sản đều đã đạt.")
    (status draft))
  (rule-metadata
    (rule-id NO-REFUSAL-MADE)
    (module refusal-and-unclaimed)
    (legal-source "Quy tắc trạng thái nội bộ")
    (description "Người đang xét được ghi nhận tường minh là không thực hiện việc từ chối nhận di sản.")
    (status draft))
  (rule-metadata
    (rule-id REFUSAL-STATUS-NORMALIZED)
    (module refusal-and-unclaimed)
    (legal-source "Quy tắc tương thích và kết nối nội bộ")
    (description "Các mô-đun hạ nguồn dùng một predicate trung gian. Kết quả suy luận từ facts chi tiết nhóm H được ưu tiên; fact `valid-refusal` của hồ sơ cũ chỉ được chuyển tiếp khi chưa có assessment nhóm H.")
    (status draft))
  (rule-metadata
    (rule-id R-H04)
    (module refusal-and-unclaimed)
    (legal-source "Điều 622 Bộ luật Dân sự 2015")
    (description "Việc tìm người hưởng theo di chúc và theo pháp luật đã được xác nhận đầy đủ, không có người đang được gọi hưởng, không có disposition còn hiệu lực cho phần này và đây là phần còn lại sau khi hoàn thành nghĩa vụ tài sản.")
    (status draft))
  (rule-metadata
    (rule-id R-I01)
    (module estate-settlement)
    (legal-source "Điều 658 Bộ luật Dân sự 2015")
    (description "Loại nghĩa vụ hoặc chi phí của từng khoản được đối chiếu với bảng tri thức 10 mức tại Điều 658. Một production rule tổng quát thực hiện phép đối chiếu; thứ tự pháp lý không được mã hóa thành mười nhánh điều kiện.")
    (status draft))
  (rule-metadata
    (rule-id R-I02)
    (module estate-settlement)
    (legal-source "Điều 659 khoản 1 Bộ luật Dân sự 2015")
    (description "Khi danh sách người được chỉ định đã đầy đủ, có từ hai người, di chúc không xác định rõ phần của từng người và không có thỏa thuận khác, hệ thống ghi nhận nguyên tắc chia đều. Việc có phần đã xác định, có thỏa thuận khác hoặc chỉ có một người làm nguyên tắc mặc định này không áp dụng.")
    (status draft))
  (rule-metadata
    (rule-id R-I03a)
    (module estate-settlement)
    (legal-source "Điều 660 khoản 1 Bộ luật Dân sự 2015")
    (description "Người đang xét đã thành thai nhưng chưa sinh tại thời điểm phân chia và graph dẫn xuất người đó thuộc cùng hàng thừa kế đang hoạt động, nên phải dành lại một phần bằng phần người thừa kế khác được hưởng.")
    (status draft))
  (rule-metadata
    (rule-id R-I03b)
    (module estate-settlement)
    (legal-source "Điều 660 khoản 1 Bộ luật Dân sự 2015")
    (description "Nếu người đã được dành suất sinh ra còn sống thì người đó được hưởng; nếu chết trước khi sinh ra thì những người thừa kế khác được hưởng phần đã dành.")
    (status draft))
  (rule-metadata
    (rule-id R-I04)
    (module estate-settlement)
    (legal-source "Điều 661 Bộ luật Dân sự 2015")
    (description "Ý chí trong di chúc hoặc thỏa thuận của tất cả người thừa kế xác định một thời hạn chưa chia. Hệ thống giữ giới hạn dưới dạng mốc ngày cụ thể, không suy ra Boolean chung chung.")
    (status draft))
  (rule-metadata
    (rule-id R-I05)
    (module estate-settlement)
    (legal-source "Điều 661 Bộ luật Dân sự 2015")
    (description "Khi có yêu cầu chia và việc chia ảnh hưởng nghiêm trọng đến đời sống của vợ hoặc chồng còn sống và gia đình, hệ thống chỉ ghi nhận quyền yêu cầu Tòa án. Thời hạn lần đầu tối đa ba năm; nếu ảnh hưởng vẫn còn thì có thể yêu cầu gia hạn một lần, tối đa ba năm.")
    (status draft))
  (rule-metadata
    (rule-id REPRESENTATION-CANDIDATE-INACTIVE)
    (module representation)
    (legal-source "Quy tắc kết nối nội bộ; liên quan Điều 620–621 và Điều 652")
    (description "Ứng viên đã chết, từ chối hợp lệ hoặc bị loại khỏi thừa kế theo pháp luật; ngoại lệ chỉ định trong di chúc không tạo quyền thế vị theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-D01)
    (module eligibility)
    (legal-source "Điều 621 khoản 1 điểm a Bộ luật Dân sự 2015")
    (description "Ứng viên có bản án về hành vi cố ý xâm phạm tính mạng, sức khỏe hoặc hành vi ngược đãi, hành hạ, xâm phạm nghiêm trọng danh dự, nhân phẩm người để lại di sản.")
    (status draft))
  (rule-metadata
    (rule-id R-D02)
    (module eligibility)
    (legal-source "Điều 621 khoản 1 điểm b Bộ luật Dân sự 2015")
    (description "Ứng viên vi phạm nghiêm trọng nghĩa vụ nuôi dưỡng người để lại di sản.")
    (status draft))
  (rule-metadata
    (rule-id R-D03)
    (module eligibility)
    (legal-source "Điều 621 khoản 1 điểm c Bộ luật Dân sự 2015")
    (description "Ứng viên bị kết án về hành vi cố ý xâm phạm tính mạng người thừa kế khác và có mục đích hưởng thêm di sản.")
    (status draft))
  (rule-metadata
    (rule-id R-D04a)
    (module eligibility)
    (legal-source "Điều 621 khoản 1 điểm d Bộ luật Dân sự 2015")
    (description "Ứng viên có hành vi lừa dối hoặc cưỡng ép người để lại di sản trong việc lập di chúc.")
    (status draft))
  (rule-metadata
    (rule-id R-D04b)
    (module eligibility)
    (legal-source "Điều 621 khoản 1 điểm d Bộ luật Dân sự 2015")
    (description "Ứng viên giả mạo, sửa, hủy hoặc che giấu di chúc nhằm hưởng di sản trái ý chí người để lại di sản.")
    (status draft))
  (rule-metadata
    (rule-id R-D05)
    (module eligibility)
    (legal-source "Điều 621 khoản 2 Bộ luật Dân sự 2015")
    (description "Dù thuộc khoản 1, người này vẫn có thể hưởng theo di chúc nếu người để lại di sản biết hành vi nhưng vẫn cho hưởng.")
    (status draft))
  (rule-metadata
    (rule-id ELIGIBILITY-BLOCKED)
    (module eligibility)
    (legal-source "Quy tắc kết nối nội bộ; dựa trên Điều 621")
    (description "Sau khi rà soát đầy đủ, một căn cứ loại trừ không có ngoại lệ được chiếu thành kết quả không được hưởng.")
    (status draft))
  (rule-metadata
    (rule-id ELIGIBILITY-CLEAR)
    (module eligibility)
    (legal-source "Quy tắc completeness nội bộ; không phải kết luận quyền hưởng cuối cùng")
    (description "Marker completeness cho biết các nhóm căn cứ Điều 621 đã được kiểm tra và không có căn cứ loại trừ nào được dẫn xuất.")
    (status draft))
  (rule-metadata
    (rule-id R-A01)
    (module inheritance-type)
    (legal-source "Điều 649 và Điều 650 khoản 1 điểm a Bộ luật Dân sự 2015")
    (description "Khi hồ sơ xác nhận người chết không để lại di chúc, phần di sản đang xét được xác định thuộc phạm vi thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-A02)
    (module inheritance-type)
    (legal-source "Điều 650 khoản 1 điểm b và khoản 2 điểm b Bộ luật Dân sự 2015")
    (description "Khi phần di sản đang xét gắn với một di chúc đã được mô-đun tính hợp pháp kết luận là không hợp pháp, phần bị ảnh hưởng được chuyển sang thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-A03)
    (module inheritance-type)
    (legal-source "Đặc tả nhóm A; đối chiếu Điều 650 Bộ luật Dân sự 2015")
    (description "Khi di chúc hợp pháp và việc định đoạt phần di sản cho người thụ hưởng có hiệu lực, hệ thống phân loại phần đó là thừa kế theo di chúc. Đây là luật TEAM_REVIEW cần đối chiếu thêm căn cứ dương, không chỉ suy ra từ các trường hợp tại Điều 650.")
    (status draft))
  (rule-metadata
    (rule-id R-A04)
    (module inheritance-type)
    (legal-source "Điều 650 khoản 1 điểm c và khoản 2 điểm c Bộ luật Dân sự 2015")
    (description "Khi người được chỉ định chết trước hoặc cùng thời điểm với người lập di chúc, hoặc cơ quan, tổ chức được hưởng không còn tồn tại lúc mở thừa kế, phần định đoạt bị ảnh hưởng áp dụng thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-A05a)
    (module inheritance-type)
    (legal-source "Điều 650 khoản 1 điểm d và khoản 2 điểm c Bộ luật Dân sự 2015")
    (description "Khi người được chỉ định không có quyền hưởng di sản và không thuộc ngoại lệ được hưởng, phần định đoạt cho người đó áp dụng thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-A05b)
    (module inheritance-type)
    (legal-source "Điều 650 khoản 1 điểm d và khoản 2 điểm c Bộ luật Dân sự 2015")
    (description "Khi người được chỉ định có việc từ chối nhận di sản hợp lệ, phần định đoạt cho người đó áp dụng thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-A06)
    (module inheritance-type)
    (legal-source "Điều 650 khoản 2 điểm a Bộ luật Dân sự 2015")
    (description "Khi tập định đoạt đã được xác nhận đầy đủ nhưng phần di sản đang xét không được định đoạt trong di chúc, phần đó áp dụng thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id SYSTEM-REGIME-CONFLICT)
    (module inheritance-type)
    (legal-source "Quy tắc kiểm soát nhất quán của hệ thống")
    (description "Cùng một phần di sản đồng thời được dẫn xuất là theo pháp luật và theo di chúc.")
    (status draft))
  (rule-metadata
    (rule-id SYSTEM-CONFLICT)
    (module will-validity)
    (legal-source "Quy tắc kiểm soát nhất quán của hệ thống")
    (description "Working memory đồng thời chứa kết luận hợp pháp và không hợp pháp cho cùng một di chúc.")
    (status draft))
  (rule-metadata
    (rule-id SYSTEM-INCOMPLETE)
    (module will-validity)
    (legal-source "Quy tắc kiểm soát tính đầy đủ của hệ thống")
    (description "Hệ thống còn ít nhất một dữ kiện bắt buộc chưa được cung cấp và chưa có kết luận hợp pháp, không hợp pháp hoặc mâu thuẫn.")
    (status draft)))
