; GENERATED FILE — do not edit directly.
; Source: knowledge-base/rule-registry.json
; Run: npm run kb:generate

(deffacts will-validity-rule-metadata
  (rule-metadata
    (rule-id FORM-ASSESSMENT-ACCEPTED)
    (module will-validity)
    (legal-source "Quy tắc chuyển tiếp nội bộ; liên quan Điều 627–636")
    (description "Từ dữ kiện di chúc bằng văn bản và chưa phát hiện khiếm khuyết hình thức, hệ thống tạm ghi nhận điều kiện hình thức đã đạt.")
    (status draft))
  (rule-metadata
    (rule-id R-B01)
    (module will-validity)
    (legal-source "Điều 630 khoản 1 điểm a Bộ luật Dân sự 2015")
    (description "Vì người lập di chúc minh mẫn, sáng suốt và không có dữ kiện về lừa dối hoặc đe dọa, hệ thống suy ra điều kiện về ý chí đã đạt.")
    (status draft))
  (rule-metadata
    (rule-id R-B02)
    (module will-validity)
    (legal-source "Điều 630 khoản 1 điểm b Bộ luật Dân sự 2015")
    (description "Vì không phát hiện nội dung bị cấm và điều kiện hình thức đã đạt, hệ thống suy ra điều kiện về nội dung và hình thức đã đạt.")
    (status draft))
  (rule-metadata
    (rule-id R-B03)
    (module will-validity)
    (legal-source "Điều 630 Bộ luật Dân sự 2015")
    (description "Khi điều kiện về ý chí, nội dung và hình thức đều đã được dẫn xuất là hợp lệ, hệ thống kết luận di chúc hợp pháp.")
    (status draft))
  (rule-metadata
    (rule-id R-B04)
    (module will-validity)
    (legal-source "Điều 630 khoản 1 điểm a Bộ luật Dân sự 2015")
    (description "Trạng thái không minh mẫn hoặc tác động trái ý chí làm điều kiện tại khoản 1 điểm a không được đáp ứng.")
    (status draft))
  (rule-metadata
    (rule-id R-B05)
    (module will-validity)
    (legal-source "Điều 630 khoản 2 Bộ luật Dân sự 2015")
    (description "Độ tuổi, hình thức văn bản và sự đồng ý của cha, mẹ hoặc người giám hộ đáp ứng yêu cầu riêng đối với người chưa thành niên.")
    (status draft))
  (rule-metadata
    (rule-id R-B06)
    (module will-validity)
    (legal-source "Điều 630 khoản 2 Bộ luật Dân sự 2015")
    (description "Người từ 15 đến dưới 18 tuổi không lập di chúc bằng văn bản hoặc không có sự đồng ý cần thiết nên không đạt yêu cầu riêng.")
    (status draft))
  (rule-metadata
    (rule-id R-B07)
    (module will-validity)
    (legal-source "Điều 630 khoản 3 Bộ luật Dân sự 2015")
    (description "Đối với người bị hạn chế thể chất hoặc không biết chữ, văn bản do người làm chứng lập và được công chứng hoặc chứng thực đáp ứng yêu cầu hình thức.")
    (status draft))
  (rule-metadata
    (rule-id R-B08)
    (module will-validity)
    (legal-source "Điều 629 khoản 2 Bộ luật Dân sự 2015")
    (description "Sau ba tháng, người lập vẫn còn sống, minh mẫn và sáng suốt nên di chúc miệng mặc nhiên bị hủy bỏ.")
    (status draft))
  (rule-metadata
    (rule-id R-B09)
    (module will-validity)
    (legal-source "Điều 630 khoản 5 Bộ luật Dân sự 2015")
    (description "Số người làm chứng, việc ghi chép, ký hoặc điểm chỉ và thời hạn xác nhận đáp ứng các điều kiện của di chúc miệng.")
    (status draft))
  (rule-metadata
    (rule-id R-C01)
    (module heir-rank)
    (legal-source "Điều 651 khoản 1 điểm a Bộ luật Dân sự 2015")
    (description "Quan hệ vợ/chồng tại thời điểm mở thừa kế, cha mẹ đẻ hoặc nuôi, và con đẻ hoặc nuôi đặt người đang xét vào nhóm ứng viên hàng thứ nhất. Kết luận này chưa tự động có nghĩa người đó được gọi hưởng.")
    (status draft))
  (rule-metadata
    (rule-id R-C02)
    (module heir-rank)
    (legal-source "Điều 651 khoản 1 điểm b Bộ luật Dân sự 2015")
    (description "Đường quan hệ huyết thống trong graph cho thấy người đang xét là ông/bà, anh/chị/em ruột hoặc cháu ruột mà người chết là ông/bà.")
    (status draft))
  (rule-metadata
    (rule-id R-C03)
    (module heir-rank)
    (legal-source "Điều 651 khoản 1 điểm c Bộ luật Dân sự 2015")
    (description "Đường quan hệ huyết thống trong graph cho thấy người đang xét là cụ, bác/chú/cậu/cô/dì, cháu ruột theo nhánh anh chị em hoặc chắt ruột của người chết.")
    (status draft))
  (rule-metadata
    (rule-id R-C04)
    (module heir-rank)
    (legal-source "Điều 651 khoản 2 Bộ luật Dân sự 2015")
    (description "Khi có từ hai người trở lên cùng được gọi hưởng ở hàng đang hoạt động, hệ thống ghi nhận nguyên tắc cùng hàng hưởng phần bằng nhau; mô-đun này chưa tính giá trị phần chia.")
    (status draft))
  (rule-metadata
    (rule-id R-C05)
    (module heir-rank)
    (legal-source "Điều 651 khoản 3 Bộ luật Dân sự 2015")
    (description "Khi đã xác định có người đủ điều kiện ở một hàng trước, ứng viên thuộc hàng sau chưa được gọi hưởng theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-C06)
    (module heir-rank)
    (legal-source "Điều 651 khoản 3 Bộ luật Dân sự 2015; kết nối Điều 621")
    (description "Chỉ sau khi danh sách ứng viên được xác nhận đầy đủ, hệ thống chọn hàng thấp nhất còn người sống, không từ chối hợp lệ và không bị loại khỏi thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id SYSTEM-RANK-CONFLICT)
    (module heir-rank)
    (legal-source "Quy tắc kiểm soát nhất quán của hệ thống")
    (description "Cùng một người được graph quan hệ dẫn xuất vào nhiều hàng khác nhau.")
    (status draft))
  (rule-metadata
    (rule-id STATUTORY-CANDIDATE-QUALIFIED)
    (module heir-rank)
    (legal-source "Quy tắc kết nối nội bộ giữa Điều 621 và Điều 651")
    (description "Ứng viên đã có hàng, còn sống, không từ chối hợp lệ và không bị loại theo Điều 621.")
    (status draft))
  (rule-metadata
    (rule-id STATUTORY-CANDIDATE-INACTIVE)
    (module heir-rank)
    (legal-source "Quy tắc kết nối nội bộ; liên quan Điều 620, Điều 621 và Điều 651")
    (description "Ứng viên đã chết trước hoặc cùng thời điểm, từ chối hợp lệ, hoặc bị Điều 621 loại khỏi thừa kế theo pháp luật. Ngoại lệ được hưởng theo di chúc không làm người đó đủ điều kiện hưởng theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id STATUTORY-CANDIDATE-UNRESOLVED)
    (module heir-rank)
    (legal-source "Quy tắc completeness nội bộ; phục vụ áp dụng Điều 651 khoản 3")
    (description "Ứng viên đã được xếp hàng nhưng chưa thể chứng minh là đủ điều kiện hoặc bị loại; vì vậy không được xem người ở hàng này là vắng mặt.")
    (status draft))
  (rule-metadata
    (rule-id REPRESENTED-CHILD-WOULD-BE-ENTITLED)
    (module representation)
    (legal-source "Quy tắc kết nối Điều 621, Điều 651 và Điều 652")
    (description "Người được thế vị là con ruột của người để lại di sản, chết trước hoặc cùng thời điểm và không bị loại theo Điều 621.")
    (status draft))
  (rule-metadata
    (rule-id REPRESENTATION-CANDIDATE-QUALIFIED)
    (module representation)
    (legal-source "Quy tắc kết nối nội bộ; liên quan Điều 620–621 và Điều 652")
    (description "Ứng viên còn sống, không từ chối hợp lệ và không bị loại theo Điều 621.")
    (status draft))
  (rule-metadata
    (rule-id REPRESENTED-GRANDCHILD-WOULD-BE-ENTITLED)
    (module representation)
    (legal-source "Quy tắc kết nối Điều 621 và Điều 652")
    (description "Người cháu nằm trong nhánh thế vị hợp lệ của người con đã chết, bản thân cũng chết trước hoặc cùng thời điểm và không bị loại theo Điều 621.")
    (status draft))
  (rule-metadata
    (rule-id R-E01)
    (module representation)
    (legal-source "Điều 652 Bộ luật Dân sự 2015")
    (description "Graph thể hiện người con của người để lại di sản đã chết trước hoặc cùng thời điểm, còn người con của họ đủ điều kiện hưởng phần thế vị.")
    (status draft))
  (rule-metadata
    (rule-id R-E02)
    (module representation)
    (legal-source "Điều 652 Bộ luật Dân sự 2015")
    (description "Graph thể hiện cả người con và người cháu trong nhánh đã chết trước hoặc cùng thời điểm, còn người chắt đủ điều kiện hưởng phần thế vị.")
    (status draft))
  (rule-metadata
    (rule-id REPRESENTATION-CANDIDATE-INACTIVE)
    (module representation)
    (legal-source "Quy tắc kết nối nội bộ; liên quan Điều 620–621 và Điều 652")
    (description "Ứng viên đã chết, từ chối hợp lệ hoặc bị loại khỏi thừa kế theo pháp luật; ngoại lệ chỉ định trong di chúc không tạo quyền thế vị theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-D01)
    (module eligibility)
    (legal-source "Điều 621 khoản 1 điểm a Bộ luật Dân sự 2015")
    (description "Ứng viên có bản án về hành vi cố ý xâm phạm tính mạng, sức khỏe hoặc hành vi ngược đãi, hành hạ, xâm phạm nghiêm trọng danh dự, nhân phẩm người để lại di sản.")
    (status draft))
  (rule-metadata
    (rule-id R-D02)
    (module eligibility)
    (legal-source "Điều 621 khoản 1 điểm b Bộ luật Dân sự 2015")
    (description "Ứng viên vi phạm nghiêm trọng nghĩa vụ nuôi dưỡng người để lại di sản.")
    (status draft))
  (rule-metadata
    (rule-id R-D03)
    (module eligibility)
    (legal-source "Điều 621 khoản 1 điểm c Bộ luật Dân sự 2015")
    (description "Ứng viên bị kết án về hành vi cố ý xâm phạm tính mạng người thừa kế khác và có mục đích hưởng thêm di sản.")
    (status draft))
  (rule-metadata
    (rule-id R-D04a)
    (module eligibility)
    (legal-source "Điều 621 khoản 1 điểm d Bộ luật Dân sự 2015")
    (description "Ứng viên có hành vi lừa dối hoặc cưỡng ép người để lại di sản trong việc lập di chúc.")
    (status draft))
  (rule-metadata
    (rule-id R-D04b)
    (module eligibility)
    (legal-source "Điều 621 khoản 1 điểm d Bộ luật Dân sự 2015")
    (description "Ứng viên giả mạo, sửa, hủy hoặc che giấu di chúc nhằm hưởng di sản trái ý chí người để lại di sản.")
    (status draft))
  (rule-metadata
    (rule-id R-D05)
    (module eligibility)
    (legal-source "Điều 621 khoản 2 Bộ luật Dân sự 2015")
    (description "Dù thuộc khoản 1, người này vẫn có thể hưởng theo di chúc nếu người để lại di sản biết hành vi nhưng vẫn cho hưởng.")
    (status draft))
  (rule-metadata
    (rule-id ELIGIBILITY-BLOCKED)
    (module eligibility)
    (legal-source "Quy tắc kết nối nội bộ; dựa trên Điều 621")
    (description "Sau khi rà soát đầy đủ, một căn cứ loại trừ không có ngoại lệ được chiếu thành kết quả không được hưởng.")
    (status draft))
  (rule-metadata
    (rule-id ELIGIBILITY-CLEAR)
    (module eligibility)
    (legal-source "Quy tắc completeness nội bộ; không phải kết luận quyền hưởng cuối cùng")
    (description "Marker completeness cho biết các nhóm căn cứ Điều 621 đã được kiểm tra và không có căn cứ loại trừ nào được dẫn xuất.")
    (status draft))
  (rule-metadata
    (rule-id R-A01)
    (module inheritance-type)
    (legal-source "Điều 649 và Điều 650 khoản 1 điểm a Bộ luật Dân sự 2015")
    (description "Khi hồ sơ xác nhận người chết không để lại di chúc, phần di sản đang xét được xác định thuộc phạm vi thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-A02)
    (module inheritance-type)
    (legal-source "Điều 650 khoản 1 điểm b và khoản 2 điểm b Bộ luật Dân sự 2015")
    (description "Khi phần di sản đang xét gắn với một di chúc đã được mô-đun tính hợp pháp kết luận là không hợp pháp, phần bị ảnh hưởng được chuyển sang thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-A03)
    (module inheritance-type)
    (legal-source "Đặc tả nhóm A; đối chiếu Điều 650 Bộ luật Dân sự 2015")
    (description "Khi di chúc hợp pháp và việc định đoạt phần di sản cho người thụ hưởng có hiệu lực, hệ thống phân loại phần đó là thừa kế theo di chúc. Đây là luật TEAM_REVIEW cần đối chiếu thêm căn cứ dương, không chỉ suy ra từ các trường hợp tại Điều 650.")
    (status draft))
  (rule-metadata
    (rule-id R-A04)
    (module inheritance-type)
    (legal-source "Điều 650 khoản 1 điểm c và khoản 2 điểm c Bộ luật Dân sự 2015")
    (description "Khi người được chỉ định chết trước hoặc cùng thời điểm với người lập di chúc, hoặc cơ quan, tổ chức được hưởng không còn tồn tại lúc mở thừa kế, phần định đoạt bị ảnh hưởng áp dụng thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-A05a)
    (module inheritance-type)
    (legal-source "Điều 650 khoản 1 điểm d và khoản 2 điểm c Bộ luật Dân sự 2015")
    (description "Khi người được chỉ định không có quyền hưởng di sản và không thuộc ngoại lệ được hưởng, phần định đoạt cho người đó áp dụng thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-A05b)
    (module inheritance-type)
    (legal-source "Điều 650 khoản 1 điểm d và khoản 2 điểm c Bộ luật Dân sự 2015")
    (description "Khi người được chỉ định có việc từ chối nhận di sản hợp lệ, phần định đoạt cho người đó áp dụng thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id R-A06)
    (module inheritance-type)
    (legal-source "Điều 650 khoản 2 điểm a Bộ luật Dân sự 2015")
    (description "Khi tập định đoạt đã được xác nhận đầy đủ nhưng phần di sản đang xét không được định đoạt trong di chúc, phần đó áp dụng thừa kế theo pháp luật.")
    (status draft))
  (rule-metadata
    (rule-id SYSTEM-REGIME-CONFLICT)
    (module inheritance-type)
    (legal-source "Quy tắc kiểm soát nhất quán của hệ thống")
    (description "Cùng một phần di sản đồng thời được dẫn xuất là theo pháp luật và theo di chúc.")
    (status draft))
  (rule-metadata
    (rule-id SYSTEM-CONFLICT)
    (module will-validity)
    (legal-source "Quy tắc kiểm soát nhất quán của hệ thống")
    (description "Working memory đồng thời chứa kết luận hợp pháp và không hợp pháp cho cùng một di chúc.")
    (status draft))
  (rule-metadata
    (rule-id SYSTEM-INCOMPLETE)
    (module will-validity)
    (legal-source "Quy tắc kiểm soát tính đầy đủ của hệ thống")
    (description "Hệ thống còn ít nhất một dữ kiện bắt buộc chưa được cung cấp và chưa có kết luận hợp pháp, không hợp pháp hoặc mâu thuẫn.")
    (status draft)))
