; Quick Logic Test CLP - Ban an so 138/2020/DS-ST (TAND TP. Quy Nhon, Tinh Binh Dinh)
; Tranh chap ve thua ke tai san cua cu Dien Hoa L (chet ngay 06/4/2008, khong de lai di chuc).
; Tai san tranh chap: 1/2 quyen su dung dat tai 197/4 duong C, TP. Quy Nhon.
; Hang thua ke thu nhat: Cu Tran Thi D (vo), cac con: Thanh H, Hoa B (1962), Hoa N, Hoa T1 (chet 2001), Hoa B (1972), Hoa T2.
; Thua ke the vi: Anh Dien Nhat L va anh Dien Duc P (con cua ong Dien Hoa T1).

(analysis-request (case-id case-01-138-2020) (subject case-01-138-2020) (module heir-rank))

; Nguoi de lai di san (Cu Dien Hoa L)
(asserted-fact (fact-id f-deceased-person) (case-id case-01-138-2020) (subject deceased-loi) (predicate deceased-person) (value true))
(asserted-fact (fact-id f-deceased-label) (case-id case-01-138-2020) (subject deceased-loi) (predicate heir-person-label) (value "Cu Dien Hoa L (Nguoi de lai di san)"))

; Trang thai vu viec & tim kiem hang thua ke
(asserted-fact (fact-id f-search-complete) (case-id case-01-138-2020) (subject case-01-138-2020) (predicate heir-search-complete) (value true))
(asserted-fact (fact-id f-has-will) (case-id case-01-138-2020) (subject case-01-138-2020) (predicate has-will) (value false))

; Phan di san (1/2 quyen su dung dat tai 197/4 duong C, TP. Quy Nhon)
(asserted-fact (fact-id f-portion-land) (case-id case-01-138-2020) (subject portion-land) (predicate estate-portion) (value true))
(asserted-fact (fact-id f-portion-label) (case-id case-01-138-2020) (subject portion-land) (predicate estate-portion-label) (value "1/2 dat tai 197/4 duong C, TP. Quy Nhon"))

; Yeu cau chia di san va thoi hieu thua ke (Dieu 623 BLDS 2015, An le 26/2018/AL)
(asserted-fact (fact-id f-limitation-subject) (case-id case-01-138-2020) (subject req-limitation) (predicate limitation-assessment-subject) (value true))
(asserted-fact (fact-id f-limitation-label) (case-id case-01-138-2020) (subject req-limitation) (predicate limitation-request-label) (value "Yeu cau chia di san thua ke quyen su dung dat"))
(asserted-fact (fact-id f-limitation-type) (case-id case-01-138-2020) (subject req-limitation) (predicate request-type) (value divide-estate))
(asserted-fact (fact-id f-limitation-asset) (case-id case-01-138-2020) (subject req-limitation) (predicate asset-type) (value immovable))
(asserted-fact (fact-id f-limitation-date) (case-id case-01-138-2020) (subject req-limitation) (predicate inheritance-opening-date) (value "2008-04-06"))

; 1. Cu Tran Thi D (Vo - sinh 1938, nguyen don)
(asserted-fact (fact-id f-d-cand) (case-id case-01-138-2020) (subject person-dien-thi-d) (predicate heir-rank-candidate) (value true))
(asserted-fact (fact-id f-d-label) (case-id case-01-138-2020) (subject person-dien-thi-d) (predicate heir-person-label) (value "Cu Tran Thi D (Vo - 1938)"))
(asserted-fact (fact-id f-d-spouse) (case-id case-01-138-2020) (subject person-dien-thi-d) (predicate spouse-at-opening) (value deceased-loi))
(asserted-fact (fact-id f-d-life) (case-id case-01-138-2020) (subject person-dien-thi-d) (predicate heir-life-status) (value alive))
(asserted-fact (fact-id f-d-refusal) (case-id case-01-138-2020) (subject person-dien-thi-d) (predicate valid-refusal) (value false))
(asserted-fact (fact-id f-d-el-cand) (case-id case-01-138-2020) (subject person-dien-thi-d) (predicate eligibility-candidate) (value true))
(asserted-fact (fact-id f-d-el-rev) (case-id case-01-138-2020) (subject person-dien-thi-d) (predicate eligibility-review-complete) (value true))

; 2. Ba Dien Thi Thanh H (Con gai - sinh 1960)
(asserted-fact (fact-id f-h-cand) (case-id case-01-138-2020) (subject person-thanh-h) (predicate heir-rank-candidate) (value true))
(asserted-fact (fact-id f-h-label) (case-id case-01-138-2020) (subject person-thanh-h) (predicate heir-person-label) (value "Ba Dien Thi Thanh H (Con - 1960)"))
(asserted-fact (fact-id f-h-parent) (case-id case-01-138-2020) (subject deceased-loi) (predicate biological-parent-of) (value person-thanh-h))
(asserted-fact (fact-id f-h-life) (case-id case-01-138-2020) (subject person-thanh-h) (predicate heir-life-status) (value alive))
(asserted-fact (fact-id f-h-refusal) (case-id case-01-138-2020) (subject person-thanh-h) (predicate valid-refusal) (value false))
(asserted-fact (fact-id f-h-el-cand) (case-id case-01-138-2020) (subject person-thanh-h) (predicate eligibility-candidate) (value true))
(asserted-fact (fact-id f-h-el-rev) (case-id case-01-138-2020) (subject person-thanh-h) (predicate eligibility-review-complete) (value true))

; 3. Ong Dien Hoa B (Con trai - sinh 1962, bi don)
(asserted-fact (fact-id f-b1-cand) (case-id case-01-138-2020) (subject person-hoa-b-1962) (predicate heir-rank-candidate) (value true))
(asserted-fact (fact-id f-b1-label) (case-id case-01-138-2020) (subject person-hoa-b-1962) (predicate heir-person-label) (value "Ong Dien Hoa B (Con - 1962)"))
(asserted-fact (fact-id f-b1-parent) (case-id case-01-138-2020) (subject deceased-loi) (predicate biological-parent-of) (value person-hoa-b-1962))
(asserted-fact (fact-id f-b1-life) (case-id case-01-138-2020) (subject person-hoa-b-1962) (predicate heir-life-status) (value alive))
(asserted-fact (fact-id f-b1-refusal) (case-id case-01-138-2020) (subject person-hoa-b-1962) (predicate valid-refusal) (value false))
(asserted-fact (fact-id f-b1-el-cand) (case-id case-01-138-2020) (subject person-hoa-b-1962) (predicate eligibility-candidate) (value true))
(asserted-fact (fact-id f-b1-el-rev) (case-id case-01-138-2020) (subject person-hoa-b-1962) (predicate eligibility-review-complete) (value true))

; 4. Ong Dien Hoa N (Con trai - sinh 1964)
(asserted-fact (fact-id f-n-cand) (case-id case-01-138-2020) (subject person-hoa-n) (predicate heir-rank-candidate) (value true))
(asserted-fact (fact-id f-n-label) (case-id case-01-138-2020) (subject person-hoa-n) (predicate heir-person-label) (value "Ong Dien Hoa N (Con - 1964)"))
(asserted-fact (fact-id f-n-parent) (case-id case-01-138-2020) (subject deceased-loi) (predicate biological-parent-of) (value person-hoa-n))
(asserted-fact (fact-id f-n-life) (case-id case-01-138-2020) (subject person-hoa-n) (predicate heir-life-status) (value alive))
(asserted-fact (fact-id f-n-refusal) (case-id case-01-138-2020) (subject person-hoa-n) (predicate valid-refusal) (value false))
(asserted-fact (fact-id f-n-el-cand) (case-id case-01-138-2020) (subject person-hoa-n) (predicate eligibility-candidate) (value true))
(asserted-fact (fact-id f-n-el-rev) (case-id case-01-138-2020) (subject person-hoa-n) (predicate eligibility-review-complete) (value true))

; 5. Ong Dien Hoa T1 (Con trai - chet 22/5/2001, chet truoc cu Loi)
(asserted-fact (fact-id f-t1-cand) (case-id case-01-138-2020) (subject person-hoa-t1) (predicate heir-rank-candidate) (value true))
(asserted-fact (fact-id f-t1-label) (case-id case-01-138-2020) (subject person-hoa-t1) (predicate heir-person-label) (value "Ong Dien Hoa T1 (Con - Chet 2001)"))
(asserted-fact (fact-id f-t1-parent) (case-id case-01-138-2020) (subject deceased-loi) (predicate biological-parent-of) (value person-hoa-t1))
(asserted-fact (fact-id f-t1-life) (case-id case-01-138-2020) (subject person-hoa-t1) (predicate heir-life-status) (value dead-before-or-same))
(asserted-fact (fact-id f-t1-refusal) (case-id case-01-138-2020) (subject person-hoa-t1) (predicate valid-refusal) (value false))
(asserted-fact (fact-id f-t1-el-cand) (case-id case-01-138-2020) (subject person-hoa-t1) (predicate eligibility-candidate) (value true))
(asserted-fact (fact-id f-t1-el-rev) (case-id case-01-138-2020) (subject person-hoa-t1) (predicate eligibility-review-complete) (value true))

; 6. Ong Dien Hoa B (Con trai - sinh 1972)
(asserted-fact (fact-id f-b2-cand) (case-id case-01-138-2020) (subject person-hoa-b-1972) (predicate heir-rank-candidate) (value true))
(asserted-fact (fact-id f-b2-label) (case-id case-01-138-2020) (subject person-hoa-b-1972) (predicate heir-person-label) (value "Ong Dien Hoa B (Con - 1972)"))
(asserted-fact (fact-id f-b2-parent) (case-id case-01-138-2020) (subject deceased-loi) (predicate biological-parent-of) (value person-hoa-b-1972))
(asserted-fact (fact-id f-b2-life) (case-id case-01-138-2020) (subject person-hoa-b-1972) (predicate heir-life-status) (value alive))
(asserted-fact (fact-id f-b2-refusal) (case-id case-01-138-2020) (subject person-hoa-b-1972) (predicate valid-refusal) (value false))
(asserted-fact (fact-id f-b2-el-cand) (case-id case-01-138-2020) (subject person-hoa-b-1972) (predicate eligibility-candidate) (value true))
(asserted-fact (fact-id f-b2-el-rev) (case-id case-01-138-2020) (subject person-hoa-b-1972) (predicate eligibility-review-complete) (value true))

; 7. Ong Dien Hoa T2 (Con trai - sinh 1974)
(asserted-fact (fact-id f-t2-cand) (case-id case-01-138-2020) (subject person-hoa-t2) (predicate heir-rank-candidate) (value true))
(asserted-fact (fact-id f-t2-label) (case-id case-01-138-2020) (subject person-hoa-t2) (predicate heir-person-label) (value "Ong Dien Hoa T2 (Con - 1974)"))
(asserted-fact (fact-id f-t2-parent) (case-id case-01-138-2020) (subject deceased-loi) (predicate biological-parent-of) (value person-hoa-t2))
(asserted-fact (fact-id f-t2-life) (case-id case-01-138-2020) (subject person-hoa-t2) (predicate heir-life-status) (value alive))
(asserted-fact (fact-id f-t2-refusal) (case-id case-01-138-2020) (subject person-hoa-t2) (predicate valid-refusal) (value false))
(asserted-fact (fact-id f-t2-el-cand) (case-id case-01-138-2020) (subject person-hoa-t2) (predicate eligibility-candidate) (value true))
(asserted-fact (fact-id f-t2-el-rev) (case-id case-01-138-2020) (subject person-hoa-t2) (predicate eligibility-review-complete) (value true))

; 8. Anh Dien Nhat L (Chau noi - sinh 1992, con ong T1, thua ke the vi)
(asserted-fact (fact-id f-l-rep-cand) (case-id case-01-138-2020) (subject person-nhat-l) (predicate representation-candidate) (value true))
(asserted-fact (fact-id f-l-label) (case-id case-01-138-2020) (subject person-nhat-l) (predicate heir-person-label) (value "Anh Dien Nhat L (Chau the vi - 1992)"))
(asserted-fact (fact-id f-t1-l-parent) (case-id case-01-138-2020) (subject person-hoa-t1) (predicate biological-parent-of) (value person-nhat-l))
(asserted-fact (fact-id f-l-life) (case-id case-01-138-2020) (subject person-nhat-l) (predicate heir-life-status) (value alive))
(asserted-fact (fact-id f-l-refusal) (case-id case-01-138-2020) (subject person-nhat-l) (predicate valid-refusal) (value false))
(asserted-fact (fact-id f-l-el-cand) (case-id case-01-138-2020) (subject person-nhat-l) (predicate eligibility-candidate) (value true))
(asserted-fact (fact-id f-l-el-rev) (case-id case-01-138-2020) (subject person-nhat-l) (predicate eligibility-review-complete) (value true))

; 9. Anh Dien Duc P (Chau noi - sinh 1995, con ong T1, thua ke the vi)
(asserted-fact (fact-id f-p-rep-cand) (case-id case-01-138-2020) (subject person-duc-p) (predicate representation-candidate) (value true))
(asserted-fact (fact-id f-p-label) (case-id case-01-138-2020) (subject person-duc-p) (predicate heir-person-label) (value "Anh Dien Duc P (Chau the vi - 1995)"))
(asserted-fact (fact-id f-t1-p-parent) (case-id case-01-138-2020) (subject person-hoa-t1) (predicate biological-parent-of) (value person-duc-p))
(asserted-fact (fact-id f-p-life) (case-id case-01-138-2020) (subject person-duc-p) (predicate heir-life-status) (value alive))
(asserted-fact (fact-id f-p-refusal) (case-id case-01-138-2020) (subject person-duc-p) (predicate valid-refusal) (value false))
(asserted-fact (fact-id f-p-el-cand) (case-id case-01-138-2020) (subject person-duc-p) (predicate eligibility-candidate) (value true))
(asserted-fact (fact-id f-p-el-rev) (case-id case-01-138-2020) (subject person-duc-p) (predicate eligibility-review-complete) (value true))
