(load "knowledge-base/templates.clp")
(load "knowledge-base/rule-metadata.clp")
(load "knowledge-base/rules/03-eligibility.clp")
(load "knowledge-base/rules/08-refusal-and-unclaimed.clp")
(load "knowledge-base/rules/06-compulsory-share.clp")
(load "knowledge-base/rules/96-compulsory-share-completeness.clp")
(load "knowledge-base/rules/97-compulsory-share-projection.clp")
(load "knowledge-base/rules/98-explanation.clp")
(reset)
(load-facts "knowledge-base/fixtures/compulsory-share.clp")
(run)
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject minor-child) (eq ?result:predicate compulsory-heir-candidate) (eq ?result:value true)))
    (any-factp ((?result module-result)) (and (eq ?result:subject minor-child) (eq ?result:predicate compulsory-heir) (eq ?result:value true))))
  then (printout t "PASS compulsory-minor-active" crlf) else (printout t "FAIL compulsory-minor-active" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject adult-child) (eq ?result:predicate compulsory-heir-candidate) (eq ?result:value true)))
    (any-factp ((?result module-result)) (and (eq ?result:subject adult-child) (eq ?result:predicate compulsory-heir) (eq ?result:value false))))
  then (printout t "PASS compulsory-adult-refusal" crlf) else (printout t "FAIL compulsory-adult-refusal" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject parent-one) (eq ?result:predicate compulsory-heir) (eq ?result:value false)))
  then (printout t "PASS compulsory-parent-excluded" crlf) else (printout t "FAIL compulsory-parent-excluded" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject capable-child) (eq ?result:predicate compulsory-heir-candidate) (eq ?result:value false)))
  then (printout t "PASS compulsory-capable-adult-not-protected" crlf) else (printout t "FAIL compulsory-capable-adult-not-protected" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject unknown-child) (eq ?result:predicate compulsory-heir-candidate) (eq ?result:value unknown)))
    (any-factp ((?missing missing-requirement)) (and (eq ?missing:subject unknown-child) (eq ?missing:predicate work-capacity-status))))
  then (printout t "PASS compulsory-open-world" crlf) else (printout t "FAIL compulsory-open-world" crlf))
(if (and
    (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-F01a))
    (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-F02))
    (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-F03))
    (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-F04)))
  then (printout t "PASS compulsory-traces" crlf) else (printout t "FAIL compulsory-traces" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject calc-minor-one) (eq ?result:predicate minimum-compulsory-share) (= ?result:value 200.0)))
    (any-factp ((?result module-result)) (and (eq ?result:subject calc-minor-one) (eq ?result:predicate minimum-share-rule-applies) (eq ?result:value true)))
    (any-factp ((?result module-result)) (and (eq ?result:subject calc-minor-one) (eq ?result:predicate compulsory-share-shortfall) (= ?result:value 100.0))))
  then (printout t "PASS compulsory-shortfall-calculation" crlf) else (printout t "FAIL compulsory-shortfall-calculation" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject calc-spouse-one) (eq ?result:predicate minimum-compulsory-share) (= ?result:value 200.0)))
    (any-factp ((?result module-result)) (and (eq ?result:subject calc-spouse-one) (eq ?result:predicate minimum-share-rule-applies) (eq ?result:value false)))
    (any-factp ((?result module-result)) (and (eq ?result:subject calc-spouse-one) (eq ?result:predicate compulsory-share-shortfall) (= ?result:value 0))))
  then (printout t "PASS compulsory-threshold-met" crlf) else (printout t "FAIL compulsory-threshold-met" crlf))
(exit)
