(load "knowledge-base/templates.clp")
(load "knowledge-base/rule-metadata.clp")
(load "knowledge-base/rules/03-eligibility.clp")
(load "knowledge-base/rules/08-refusal-and-unclaimed.clp")
(load "knowledge-base/rules/04-heir-rank.clp")
(load "knowledge-base/rules/09-estate-settlement.clp")
(load "knowledge-base/rules/11-estate-vnd.clp")
(load "knowledge-base/rules/06-compulsory-share.clp")
(load "knowledge-base/rules/96-compulsory-share-completeness.clp")
(load "knowledge-base/rules/97-compulsory-share-projection.clp")
(load "knowledge-base/rules/98-explanation.clp")
(reset)
(load-facts "knowledge-base/fixtures/estate-vnd.clp")
(assert (analysis-request (case-id estate-vnd-case) (subject estate-vnd-calculation) (module compulsory-share)))
(run)

(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject child-one) (eq ?result:predicate hypothetical-statutory-share-vnd) (= ?result:value 850000000)))
    (any-factp ((?result module-result)) (and (eq ?result:subject child-one) (eq ?result:predicate minimum-compulsory-share-vnd) (= ?result:value 566666666)))
    (any-factp ((?result module-result)) (and (eq ?result:subject child-one) (eq ?result:predicate minimum-compulsory-share-rounding-remainder-numerator) (= ?result:value 2)))
    (any-factp ((?result module-result)) (and (eq ?result:subject child-one) (eq ?result:predicate compulsory-share-shortfall-vnd) (= ?result:value 466666666)))
    (any-factp ((?result module-result)) (and (eq ?result:subject child-one) (eq ?result:predicate minimum-share-rule-applies-vnd) (eq ?result:value true))))
  then (printout t "PASS compulsory-share-vnd-auto-statutory-share" crlf) else (printout t "FAIL compulsory-share-vnd-auto-statutory-share" crlf))

(exit)
