(load "knowledge-base/templates.clp")
(load "knowledge-base/rule-metadata.clp")
(load "knowledge-base/rules/09-estate-settlement.clp")
(load "knowledge-base/rules/99-estate-settlement-completeness.clp")
(load "knowledge-base/rules/99-estate-settlement-projection.clp")
(load "knowledge-base/rules/98-explanation.clp")
(reset)
(load-facts "knowledge-base/fixtures/estate-settlement.clp")
(run)
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject funeral-one) (eq ?result:predicate payment-priority) (= ?result:value 1)))
    (any-factp ((?result module-result)) (and (eq ?result:subject tax-one) (eq ?result:predicate payment-priority) (= ?result:value 7)))
    (any-factp ((?trace inference-trace)) (and (eq ?trace:subject funeral-one) (eq ?trace:rule-id R-I01))))
  then (printout t "PASS estate-settlement-priority-knowledge" crlf) else (printout t "FAIL estate-settlement-priority-knowledge" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject unknown-one) (eq ?result:value unknown)))
    (any-factp ((?missing missing-requirement)) (and (eq ?missing:subject unknown-one) (eq ?missing:predicate obligation-type))))
  then (printout t "PASS estate-settlement-open-world" crlf) else (printout t "FAIL estate-settlement-open-world" crlf))
(exit)
