(load "knowledge-base/templates.clp")
(load "knowledge-base/rule-metadata.clp")
(load "knowledge-base/rules/04-heir-rank.clp")
(load "knowledge-base/rules/93-heir-rank-completeness.clp")
(load "knowledge-base/rules/95-heir-rank-projection.clp")
(load "knowledge-base/rules/98-explanation.clp")
(reset)
(load-facts "knowledge-base/fixtures/heir-rank-first.clp")
(run)
(if (= (length$ (find-all-facts ((?result module-result)) (eq ?result:value rank-1))) 5)
  then (printout t "PASS heir-rank-first" crlf) else (printout t "FAIL heir-rank-first" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject unknown-one) (eq ?result:value unknown)))
  then (printout t "PASS heir-rank-unknown" crlf) else (printout t "FAIL heir-rank-unknown" crlf))
(if (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-C01))
  then (printout t "PASS heir-rank-trace" crlf) else (printout t "FAIL heir-rank-trace" crlf))
(exit)
