(load "knowledge-base/templates.clp")
(load "knowledge-base/rule-metadata.clp")
(load "knowledge-base/rules/03-eligibility.clp")
(load "knowledge-base/rules/08-refusal-and-unclaimed.clp")
(load "knowledge-base/rules/04-heir-rank.clp")
(load "knowledge-base/rules/93-heir-rank-completeness.clp")
(load "knowledge-base/rules/95-heir-rank-projection.clp")
(load "knowledge-base/rules/98-explanation.clp")
(reset)
(load-facts "knowledge-base/fixtures/heir-rank-first.clp")
(run)
(if (= (length$ (find-all-facts ((?result module-result)) (eq ?result:value rank-1))) 5)
  then (printout t "PASS heir-rank-first" crlf) else (printout t "FAIL heir-rank-first" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject unknown-one) (eq ?result:value unknown)))
  then (printout t "PASS heir-rank-unknown" crlf) else (printout t "FAIL heir-rank-unknown" crlf))
(if (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-C01))
  then (printout t "PASS heir-rank-trace" crlf) else (printout t "FAIL heir-rank-trace" crlf))

(reset)
(load-facts "knowledge-base/fixtures/heir-rank-active-second.clp")
(run)
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject grandparent-one) (eq ?result:predicate candidate-heir-rank) (eq ?result:value rank-2)))
    (any-factp ((?result module-result)) (and (eq ?result:subject great-grandchild-one) (eq ?result:predicate candidate-heir-rank) (eq ?result:value rank-3))))
  then (printout t "PASS heir-rank-two-three" crlf) else (printout t "FAIL heir-rank-two-three" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject case-rank-two-active) (eq ?result:predicate active-heir-rank) (eq ?result:value rank-2)))
  then (printout t "PASS heir-rank-active-second" crlf) else (printout t "FAIL heir-rank-active-second" crlf))
(if (= (length$ (find-all-facts ((?result module-result)) (and (eq ?result:predicate called-to-inherit) (eq ?result:value true)))) 2)
  then (printout t "PASS heir-rank-call-same-rank" crlf) else (printout t "FAIL heir-rank-call-same-rank" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject spouse-one) (eq ?result:predicate called-to-inherit) (eq ?result:value false)))
    (any-factp ((?result module-result)) (and (eq ?result:subject great-grandchild-one) (eq ?result:predicate called-to-inherit) (eq ?result:value false))))
  then (printout t "PASS heir-rank-inactive-and-later" crlf) else (printout t "FAIL heir-rank-inactive-and-later" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:predicate equal-share-principle-applies) (eq ?result:value true)))
  then (printout t "PASS heir-rank-equal-share-principle" crlf) else (printout t "FAIL heir-rank-equal-share-principle" crlf))
(exit)
