(load "knowledge-base/templates.clp")
(load "knowledge-base/rule-metadata.clp")
(load "knowledge-base/rules/01-will-validity.clp")
(load "knowledge-base/rules/08-refusal-and-unclaimed.clp")
(load "knowledge-base/rules/02-inheritance-type.clp")
(load "knowledge-base/rules/91-inheritance-type-completeness.clp")
(load "knowledge-base/rules/97-inheritance-type-projection.clp")
(load "knowledge-base/rules/98-explanation.clp")

(deffunction test-regime (?fixture ?case-id ?value ?rule-id ?label)
  (reset)
  (load-facts ?fixture)
  (run)
  (if (and
        (any-factp ((?result module-result))
          (and (eq ?result:case-id ?case-id) (eq ?result:subject portion-one)
               (eq ?result:module inheritance-type) (eq ?result:predicate inheritance-regime)
               (eq ?result:value ?value)))
        (any-factp ((?trace inference-trace))
          (and (eq ?trace:case-id ?case-id) (eq ?trace:subject portion-one)
               (eq ?trace:rule-id ?rule-id))))
    then (printout t "PASS " ?label crlf)
    else (printout t "FAIL " ?label crlf)))

(test-regime "knowledge-base/fixtures/inheritance-no-will.clp" case-no-will statutory R-A01 inheritance-no-will)
(test-regime "knowledge-base/fixtures/inheritance-invalid-will.clp" case-invalid-will statutory R-A02 inheritance-invalid-will)
(test-regime "knowledge-base/fixtures/inheritance-testamentary.clp" case-testamentary testamentary R-A03 inheritance-testamentary)
(test-regime "knowledge-base/fixtures/inheritance-dead-beneficiary.clp" case-dead-beneficiary statutory R-A04 inheritance-dead-beneficiary)
(test-regime "knowledge-base/fixtures/inheritance-disqualified.clp" case-disqualified statutory R-A05a inheritance-disqualified)
(test-regime "knowledge-base/fixtures/inheritance-refusal.clp" case-refusal statutory R-A05b inheritance-refusal)
(test-regime "knowledge-base/fixtures/inheritance-undisposed.clp" case-undisposed statutory R-A06 inheritance-undisposed)

(reset)
(load-facts "knowledge-base/fixtures/inheritance-unknown.clp")
(run)
(if (and
      (any-factp ((?result module-result))
        (and (eq ?result:case-id case-inheritance-unknown) (eq ?result:value unknown)))
      (any-factp ((?missing missing-requirement))
        (and (eq ?missing:case-id case-inheritance-unknown) (eq ?missing:predicate has-will))))
  then (printout t "PASS inheritance-unknown" crlf)
  else (printout t "FAIL inheritance-unknown" crlf))

(exit)
