(load "knowledge-base/templates.clp")
(load "knowledge-base/rule-metadata.clp")
(load "knowledge-base/rules/10-limitation.clp")
(load "knowledge-base/rules/99-limitation-completeness.clp")
(load "knowledge-base/rules/99-limitation-projection.clp")
(load "knowledge-base/rules/98-explanation.clp")
(reset)
(load-facts "knowledge-base/fixtures/limitation.clp")
(run)
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject immovable-request) (= ?result:value 30)))
    (any-factp ((?result module-result)) (and (eq ?result:subject movable-request) (= ?result:value 10)))
    (any-factp ((?trace inference-trace)) (and (eq ?trace:subject immovable-request) (eq ?trace:rule-id R-J01))))
  then (printout t "PASS limitation-estate-division-periods" crlf) else (printout t "FAIL limitation-estate-division-periods" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject right-request) (= ?result:value 10)))
    (any-factp ((?result module-result)) (and (eq ?result:subject obligation-request) (= ?result:value 3))))
  then (printout t "PASS limitation-other-request-periods" crlf) else (printout t "FAIL limitation-other-request-periods" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject unknown-request) (eq ?result:value unknown)))
    (any-factp ((?missing missing-requirement)) (and (eq ?missing:subject unknown-request) (eq ?missing:predicate asset-type)))
    (any-factp ((?missing missing-requirement)) (and (eq ?missing:subject unknown-request) (eq ?missing:predicate inheritance-opening-date))))
  then (printout t "PASS limitation-open-world" crlf) else (printout t "FAIL limitation-open-world" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject managed-asset) (eq ?result:predicate post-limitation-recipient) (eq ?result:value managing-heir)))
    (any-factp ((?trace inference-trace)) (and (eq ?trace:subject managed-asset) (eq ?trace:rule-id R-J05))))
  then (printout t "PASS limitation-managing-heir" crlf) else (printout t "FAIL limitation-managing-heir" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject possessed-asset) (eq ?result:value qualified-possessor)))
    (any-factp ((?trace inference-trace)) (and (eq ?trace:subject possessed-asset) (eq ?trace:rule-id R-J06))))
  then (printout t "PASS limitation-qualified-possessor" crlf) else (printout t "FAIL limitation-qualified-possessor" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject state-asset) (eq ?result:value state)))
    (any-factp ((?trace inference-trace)) (and (eq ?trace:subject state-asset) (eq ?trace:rule-id R-J07))))
  then (printout t "PASS limitation-state-after-complete-search" crlf) else (printout t "FAIL limitation-state-after-complete-search" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject outcome-unknown-asset) (eq ?result:value unknown)))
    (any-factp ((?missing missing-requirement)) (and (eq ?missing:subject outcome-unknown-asset) (eq ?missing:predicate managing-heir-search-complete))))
  then (printout t "PASS limitation-outcome-open-world" crlf) else (printout t "FAIL limitation-outcome-open-world" crlf))
(exit)
