(load "knowledge-base/templates.clp")
(load "knowledge-base/rule-metadata.clp")
(load "knowledge-base/rules/01-will-validity.clp")
(load "knowledge-base/rules/90-will-validity-completeness.clp")
(load "knowledge-base/rules/98-explanation.clp")
(load "knowledge-base/rules/99-result-projection.clp")

(reset)
(load-facts "knowledge-base/fixtures/logic-test/complete.clp")
(run)
(if (any-factp ((?result module-result))
      (and (eq ?result:case-id logic-test-complete) (eq ?result:predicate valid-will) (eq ?result:value true)))
  then (printout t "PASS logic-test-complete" crlf)
  else (printout t "FAIL logic-test-complete" crlf))

(reset)
(load-facts "knowledge-base/fixtures/logic-test/unknown-missing.clp")
(run)
(if (and
      (any-factp ((?result module-result))
        (and (eq ?result:case-id logic-test-unknown) (eq ?result:predicate valid-will) (eq ?result:value unknown)))
      (any-factp ((?missing missing-requirement))
        (and (eq ?missing:case-id logic-test-unknown) (eq ?missing:predicate undue-influence)))
      (any-factp ((?missing missing-requirement))
        (and (eq ?missing:case-id logic-test-unknown) (eq ?missing:predicate formal-defect))))
  then (printout t "PASS logic-test-unknown-missing" crlf)
  else (printout t "FAIL logic-test-unknown-missing" crlf))

(reset)
(load-facts "knowledge-base/fixtures/logic-test/conflict.clp")
(run)
(if (any-factp ((?result module-result))
      (and (eq ?result:case-id logic-test-conflict) (eq ?result:predicate valid-will) (eq ?result:value conflict)))
  then (printout t "PASS logic-test-conflict" crlf)
  else (printout t "FAIL logic-test-conflict" crlf))

(exit)
