(load "knowledge-base/templates.clp")
(load "knowledge-base/rule-metadata.clp")
(load "knowledge-base/rules/03-eligibility.clp")
(load "knowledge-base/rules/04-heir-rank.clp")
(load "knowledge-base/rules/08-refusal-and-unclaimed.clp")
(load "knowledge-base/rules/98-refusal-and-unclaimed-completeness.clp")
(load "knowledge-base/rules/99-refusal-and-unclaimed-projection.clp")
(load "knowledge-base/rules/98-explanation.clp")
(reset)
(load-facts "knowledge-base/fixtures/refusal-and-unclaimed.clp")
(run)
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject person-valid) (eq ?result:predicate valid-refusal) (eq ?result:value true)))
    (any-factp ((?trace inference-trace)) (and (eq ?trace:subject person-valid) (eq ?trace:rule-id R-H01)))
    (any-factp ((?trace inference-trace)) (and (eq ?trace:subject person-valid) (eq ?trace:rule-id R-H03))))
  then (printout t "PASS refusal-valid-composed" crlf) else (printout t "FAIL refusal-valid-composed" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject person-avoid) (eq ?result:value false)))
    (any-factp ((?trace inference-trace)) (and (eq ?trace:subject person-avoid) (eq ?trace:rule-id R-H02))))
  then (printout t "PASS refusal-avoid-obligation" crlf) else (printout t "FAIL refusal-avoid-obligation" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject person-missing) (eq ?result:value unknown)))
    (any-factp ((?missing missing-requirement)) (and (eq ?missing:subject person-missing) (eq ?missing:predicate refusal-notice-recipient))))
  then (printout t "PASS refusal-open-world" crlf) else (printout t "FAIL refusal-open-world" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject portion-state) (eq ?result:value state)))
    (any-factp ((?trace inference-trace)) (and (eq ?trace:subject portion-state) (eq ?trace:rule-id R-H04))))
  then (printout t "PASS unclaimed-state" crlf) else (printout t "FAIL unclaimed-state" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject portion-claimed) (eq ?result:value unknown)))
  then (printout t "PASS claimed-portion-not-state" crlf) else (printout t "FAIL claimed-portion-not-state" crlf))
(exit)
