(load "knowledge-base/templates.clp")
(load "knowledge-base/rule-metadata.clp")
(load "knowledge-base/rules/03-eligibility.clp")
(load "knowledge-base/rules/05-representation.clp")
(load "knowledge-base/rules/94-representation-completeness.clp")
(load "knowledge-base/rules/95-representation-projection.clp")
(load "knowledge-base/rules/98-explanation.clp")
(reset)
(load-facts "knowledge-base/fixtures/representation.clp")
(run)
(if (any-factp ((?result module-result)) (and (eq ?result:subject grandchild-one) (eq ?result:predicate inherits-by-representation) (eq ?result:value true)))
  then (printout t "PASS representation-grandchild" crlf) else (printout t "FAIL representation-grandchild" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject great-grandchild-one) (eq ?result:predicate inherits-by-representation) (eq ?result:value true)))
  then (printout t "PASS representation-great-grandchild" crlf) else (printout t "FAIL representation-great-grandchild" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject inactive-one) (eq ?result:value false)))
  then (printout t "PASS representation-inactive" crlf) else (printout t "FAIL representation-inactive" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject unknown-one) (eq ?result:value unknown)))
  then (printout t "PASS representation-unknown" crlf) else (printout t "FAIL representation-unknown" crlf))
(if (and (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-E01)) (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-E02)))
  then (printout t "PASS representation-traces" crlf) else (printout t "FAIL representation-traces" crlf))
(exit)
