(load "knowledge-base/templates.clp")
(load "knowledge-base/rule-metadata.clp")
(load "knowledge-base/rules/03-eligibility.clp")
(load "knowledge-base/rules/05-representation.clp")
(load "knowledge-base/rules/94-representation-completeness.clp")
(load "knowledge-base/rules/95-representation-projection.clp")
(load "knowledge-base/rules/98-explanation.clp")
(reset)
(load-facts "knowledge-base/fixtures/representation.clp")
(run)
(if (any-factp ((?result module-result)) (and (eq ?result:subject grandchild-one) (eq ?result:predicate inherits-by-representation) (eq ?result:value true)))
  then (printout t "PASS representation-grandchild" crlf) else (printout t "FAIL representation-grandchild" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject great-grandchild-one) (eq ?result:predicate inherits-by-representation) (eq ?result:value true)))
  then (printout t "PASS representation-great-grandchild" crlf) else (printout t "FAIL representation-great-grandchild" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject inactive-one) (eq ?result:value false)))
  then (printout t "PASS representation-inactive" crlf) else (printout t "FAIL representation-inactive" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject unknown-one) (eq ?result:value unknown)))
  then (printout t "PASS representation-unknown" crlf) else (printout t "FAIL representation-unknown" crlf))
(if (and (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-E01)) (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-E02)))
  then (printout t "PASS representation-traces" crlf) else (printout t "FAIL representation-traces" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject adopted-child-one) (eq ?result:predicate adoption-inheritance-basis) (eq ?result:value true)))
    (any-factp ((?result module-result)) (and (eq ?result:subject adoptive-parent-one) (eq ?result:predicate adoption-inheritance-basis) (eq ?result:value true))))
  then (printout t "PASS adoption-reciprocal-basis" crlf) else (printout t "FAIL adoption-reciprocal-basis" crlf))
(if (any-factp ((?result module-result)) (and (eq ?result:subject adopted-child-one) (eq ?result:predicate dual-parentage-inheritance-basis) (eq ?result:value true)))
  then (printout t "PASS adoption-dual-basis" crlf) else (printout t "FAIL adoption-dual-basis" crlf))
(if (and (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-E03a)) (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-E03b)))
  then (printout t "PASS adoption-traces" crlf) else (printout t "FAIL adoption-traces" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject step-child-positive) (eq ?result:predicate step-relationship-inheritance-basis) (eq ?result:value true)))
    (any-factp ((?result module-result)) (and (eq ?result:subject step-parent-positive) (eq ?result:predicate step-relationship-inheritance-basis) (eq ?result:value true))))
  then (printout t "PASS step-reciprocal-basis" crlf) else (printout t "FAIL step-reciprocal-basis" crlf))
(if (and
    (any-factp ((?result module-result)) (and (eq ?result:subject step-child-negative) (eq ?result:predicate eligible-by-step-relationship) (eq ?result:value false)))
    (any-factp ((?result module-result)) (and (eq ?result:subject step-parent-negative) (eq ?result:predicate eligible-by-step-relationship) (eq ?result:value false))))
  then (printout t "PASS step-explicit-negative" crlf) else (printout t "FAIL step-explicit-negative" crlf))
(if (and
    (any-factp ((?missing missing-requirement)) (and (eq ?missing:subject step-child-unknown) (eq ?missing:predicate step-care-status)))
    (not (any-factp ((?result module-result)) (eq ?result:subject step-child-unknown))))
  then (printout t "PASS step-open-world-missing" crlf) else (printout t "FAIL step-open-world-missing" crlf))
(if (and (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-E04)) (any-factp ((?trace inference-trace)) (eq ?trace:rule-id R-E05)))
  then (printout t "PASS step-traces" crlf) else (printout t "FAIL step-traces" crlf))
(exit)
